
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports: 
      - 1972
      - 62773:52773
      - 63773
    volumes:
      - ./:/irisdev/app
