zn "%SYS"

// Unexpire passwords and set up passwordless mode to simplify dev use.
// ** Comment out these two line for Production use **
do ##class(Security.Users).UnExpireUserPasswords("*")
zpm "install passwordless"

// Enable callin for Embedded Python
do ##class(Security.Services).Get("%Service_CallIn",.prop)
set prop("Enabled")=1
set prop("AutheEnabled")=48
do ##class(Security.Services).Modify("%Service_CallIn",.prop)

// create IRISAPP namespace

zn "HSLIB"

// Install a Foundation namespace and change to it
Do ##class(HS.Util.Installer.Foundation).Install("IRISAPP")


zn "IRISAPP"
set ^UnitTest("TestDirectory")="/opt/irisapp"    
zpm "load /home/irisowner/dev -v":1:1

halt
