Class CCD.Visualizer.Data.HL7Message01 Extends %RegisteredObject
{

XData HL7Message
{
<test><![CDATA[
MSH|^~\&|FRM|FRM5T|SYSA|SYSA|202207121010||OUL^R22^OUL_R22|1234567|P|2.5|||||GBR||EN
PID|||123456789^^^NHS^NH~12345^^^774^PI||SMITH^BOB^^^||19830501|M||||||||||||||||||||||N
PV1||N|ANT5TREE^^^^^^^^MH Anticoagulant Clinic,||||C123546^Bowden^S M^^^Dr|||101|ANT5T^^^^^^^^Harbor|||||||||||||||||||||||||||||||||20220712101010
SPM|1|^62000001||03^PLA-CIT^DDN|||||||||||||20220712101010|20220712101010
OBR|1||120000000001^DDN|^International normalised ratio (INR) dose^RC^B0281^INRD^TCL||20220712101010||||||||||C123546^Bowden^S M^^^Dr|||||1|20220712101010||B|C|||||||tim223|||||||||||||||HNM^Haematology(Multiple T/S)^^AUTH
ORC|SC||120000000001^DDN||||||20220712101010|||C123546^Bowden^S M^^^Dr|||||||||Mariden University Health Board^^ANT5|||||||N
OBX|1|SN|42QE.^International normalised ratio^RC^B0700^INR^TCL|1|^1.6|ratio^^TCL||N|||C|||20150519122300||tim223
OBX|2|TX|^Warfarin Dose^RC^B0850^DOSE^TCL|2||||N|||C|||20220712101010||tim223
NTE|1|L|INR: 1.6 Target 3.0 - 4.0  L
NTE|2|L|Full Dosing Instruction:
NTE|3|L|7 mg DAILY
NTE|4|L|Next Test: 16/07/2022
]]></test>
}

}
