/** Placeholder used so escaped \F\ in field values don't break segment split. */
const ESCAPED_FIELD_PLACEHOLDER = '\u0001';

/**
 * Split a segment line by field separator (|), respecting HL7 escape \F\ (literal pipe in value).
 * @param {string} segment - One segment line (e.g. "PID|1||123^abc")
 * @returns {string[]} [type, field1, field2, ...]
 */
function splitSegmentFields(segment) {
  const withPlaceholder = segment.replace(/\\F\\/g, ESCAPED_FIELD_PLACEHOLDER);
  const parts = withPlaceholder.split('|');
  return parts.map((value) => value.replace(new RegExp(ESCAPED_FIELD_PLACEHOLDER, 'g'), '|'));
}

/**
 * @param {string} message
 * @returns {{ type: string; raw: string; fields: Array<{ fieldNumber: number; value: string; description: string }> }[]}
 */
// export const parseHL7Message = (message) => {
//   if (!message) return [];

//   const segments = message.split('\n').filter(Boolean);

//   return segments.map((segment) => {
//     const allParts = splitSegmentFields(segment);
//     const [type, ...fieldValues] = allParts;

//     return {
//       type,
//       raw: segment,
//       fields: fieldValues.map((value, index) => ({
//         fieldNumber: index + 1,
//         value,
//         description: getFieldDescription(type, index + 1),
//       })),
//     };
//   });
// };

export function parseHL7Message(rawMessage) {
  if (!rawMessage) return [];

  const lines = rawMessage
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);

  if (!lines.length) return [];

  // --- Extract separators from MSH ---
  const mshLine = lines[0];
  const fieldSep = mshLine[3];
  const encodingChars = mshLine.substring(4, 8);

  const separators = {
    field: fieldSep,
    component: encodingChars[0],
    repetition: encodingChars[1],
    escape: encodingChars[2],
    subcomponent: encodingChars[3],
  };

  // --- Parse segments ---
  return lines.map((line) => {
    const segmentType = line.substring(0, 3);
    const rawFields = line.split(separators.field);

    if (segmentType === 'MSH') {
      // MSH-1 = field separator (char after "MSH"); MSH-2 = encoding chars (4 chars); rest align with HL7 field numbers 3+
      const mshFieldSep = line[3];
      const mshEncoding = line.substring(4, 8);

      const fields = [
        {
          raw: mshFieldSep,
          fieldNumber: 1,
          parsed: atomicParsed(mshFieldSep),
        },
        {
          raw: mshEncoding,
          fieldNumber: 2,
          parsed: atomicParsed(mshEncoding),
        },
        ...rawFields.slice(2).map((value, index) => ({
          raw: value,
          fieldNumber: index + 3,
          parsed: parseField(value, separators),
        })),
      ];

      return {
        type: segmentType,
        separators,
        fields,
      };
    }

    const fields = rawFields.slice(1).map((value, index) => ({
      raw: value,
      fieldNumber: index + 1,
      parsed: parseField(value, separators),
    }));

    return {
      type: segmentType,
      separators,
      fields,
    };
  });
}

function parseField(value, sep) {
  if (!value) return [];

  return value.split(sep.repetition).map((repeat) =>
    repeat.split(sep.component).map((component) =>
      component.split(sep.subcomponent)
    )
  );
}

/** One repetition, one component, one subcomponent — avoids splitting MSH-2 on ^ ~ \\ & */
function atomicParsed(value) {
  return [[[value]]];
}

/**
 * HL7 version 2.5.1 field descriptions.
 * @param {string} segmentType
 * @param {number} fieldIndex - HL7 field number (1-based)
 * @returns {string}
 */
export function getFieldDescription(segmentType, fieldIndex) {
  const descriptions = {
    MSH: {
      1: 'Field Separator',
      2: 'Encoding Characters',
      3: 'Sending Application',
      4: 'Sending Facility',
      5: 'Receiving Application',
      6: 'Receiving Facility',
      7: 'Message DateTime',
      8: 'Security',
      9: 'Message Type',
      10: 'Message Control ID',
      11: 'Processing ID',
      12: 'Version ID',
    },
    PID: {
      1: 'Set ID',
      2: 'Patient ID',
      3: 'Patient Identifier List',
      4: 'Alternate Patient ID',
      5: 'Patient Name',
      6: "Mother's Maiden Name",
      7: 'Date/Time of Birth',
      8: 'Administrative Sex',
      9: 'Patient Alias',
      10: 'Race',
      11: 'Patient Address',
      12: 'County Code',
      13: 'Phone Number - Home',
      14: 'Phone Number - Business',
      15: 'Primary Language',
      16: 'Martial Status',
      17: 'Religion',
      18: 'Patient Account Number',
      19: 'SSN Number - Patient',
      20: "Driver's License Number",
      21: "Mother's Identifier",
      22: 'Ethnic Group',
      23: 'Birth Place',
      24: 'Multiple Birth Indicator',
      25: 'Birth Order',
      26: 'Citizenship',
      27: 'Veterans Military Status',
      28: 'Nationality',
      29: 'Patient Death Date and Time',
      30: 'Patient Death Indicator',
    },
    OBR: {
      1: 'Set ID',
      2: 'Order Number',
      3: 'Filler Order Number',
      4: 'Universal Service Identifier',
      5: 'Priority',
      6: 'Requested Date/Time',
      7: 'Observation Date/Time',
      8: 'Observation End Date/Time',
      9: 'Collection Volume',
      10: 'Collector Identifier',
      11: 'Specimen Action Code',
      12: 'Danger Code',
      13: 'Relevant Clinical Information',
      14: 'Specimen Received Date/Time',
      15: 'Specimen Source',
      16: 'Ordering Provider',
      17: 'Order Callback Phone Number',
      18: 'Placer Field 1',
      19: 'Placer Field 2',
      20: 'Filler Field 1',
      21: 'Filler Field 2',
      22: 'Results Rpt/Status Chng - Date/Time',
      23: 'Charge to Practice',
      24: 'Diagnostic Serv Sect ID',
      25: 'Result Status',
      26: 'Parent Result',
      27: 'Quantity/Timing',
      28: 'Result Copies To',
      29: 'Parent',
      30: 'Transportation Mode',
      31: 'Reason for Study',
      32: 'Principal Result Interpreter',
      33: 'Assistant Result Interpreter',
      34: 'Technician',
      35: 'Transcriptionist',
      36: 'Scheduled Date/Time',
      37: 'Number of Sample Containers',
      38: 'Transport Logistics of Collected Sample',
      39: "Collector's Comment",
      40: 'Transport Arrangement Responsibility',
      41: 'Transport Arranged',
      42: 'Escort Required',
      43: 'Planned Patient Transport Comment',
      44: 'Procedure Code',
      45: 'Procedure Code Modifier',
      46: 'Placer Supplemental Service Information',
    },
    EVN: {
      1: 'Event Type Code',
      2: 'Recorded Date/Time',
      3: 'Date/Time Planned Event',
      4: 'Event Reason Code',
      5: 'Operator ID',
      6: 'Event Occurred',
    },
    OBX: {
      1: 'Set ID',
      2: 'Value Type',
      3: 'Observation Identifier',
      4: 'Observation Sub-ID',
      5: 'Observation Value',
      6: 'Units',
      7: 'References Range',
      8: 'Abnormal Flags',
      9: 'Probability',
      10: 'Nature of Abnormal Test',
      11: 'Observation Result Status',
      12: 'Effective Date of Reference Range',
      13: 'User Defined Access Checks',
      14: 'Date/Time of the Observation',
      15: "Producer's ID",
      16: 'Responsible Observer',
      17: 'Observation Method',
      18: 'Equipment Instance Identifier',
      19: 'Date/Time of the Analysis',
    },
    RXR: {
      1: 'Route',
      2: 'Site Administered',
      3: 'Administration Device',
      4: 'Administration Method',
      5: 'Routing Instructions',
    },
    RXA: {
      1: 'Give Sub-ID Counter',
      2: 'Administration Sub-ID Counter',
      3: 'Date/Time Start of Administration',
      4: 'Date/Time End of Administration',
      5: 'Administered Code',
      6: 'Administered Amount',
      7: 'Administered Units',
      8: 'Administering Provider',
      9: 'Administration Notes',
      10: 'Completion Status',
    },
    TQ1: {
      1: 'Set ID',
      2: 'Quantity',
      3: 'Repeat Pattern',
      4: 'Explicit Time',
      5: 'Relative Time and Units',
      6: 'Service Duration',
      7: 'Start date/time',
      8: 'End date/time',
      9: 'Priority',
      10: 'Condition text',
      11: 'Text instruction',
      12: 'Conjunction',
      13: 'Occurrence duration',
      14: 'Total occurrences',
    },
    FT1: {
      1: 'Set ID',
      2: 'Transaction ID',
      3: 'Transaction Batch ID',
      4: 'Transaction Date',
      5: 'Transaction Posting Date',
      6: 'Transaction Type',
      7: 'Transaction Code',
      8: 'Transaction Description',
      9: 'Transaction Description - Alt',
      10: 'Transaction Quantity',
      11: 'Transaction Amount - Extended',
      12: 'Transaction Amount - Unit',
      13: 'Department Code',
      14: 'Insurance Plan ID',
      15: 'Insurance Amount',
      16: 'Assigned Patient Location',
      17: 'Fee Schedule',
      18: 'Patient Type',
      19: 'Diagnosis Code - FT1',
      20: 'Performed By Code',
      21: 'Ordered By Code',
      22: 'Unit Cost',
      23: 'Filler Order Number',
      24: 'Entered By Code',
      25: 'Procedure Code',
      26: 'Procedure Code Modifier',
      27: 'Advanced Beneficiary Notice Code',
      28: 'Medically Necessary Duplicate Procedure Reason.',
      29: 'NDC Code',
      30: 'Payment Reference ID',
    },
    PR1: {
      1: 'Set ID',
      2: 'Procedure Coding Method',
      3: 'Procedure Code',
      4: 'Procedure Description',
      5: 'Procedure Date/Time',
      6: 'Procedure Functional Type',
      7: 'Procedure Minutes',
      8: 'Anesthesiologist',
      9: 'Anesthesia Code',
      10: 'Anesthesia Minutes',
      11: 'Surgeon',
      12: 'Procedure Practitioner',
      13: 'Consent Code',
      14: 'Procedure Priority',
      15: 'Associated Diagnosis Code',
      16: 'Procedure Code Modifier',
      17: 'Procedure DRG Type',
      18: 'Tissue Type Code',
      19: 'Procedure Identifier',
      20: 'Procedure Action Code',
    },
    TXA: {
      1: 'Set ID',
      2: 'Document Type',
      3: 'Document Content Presentation',
      4: 'Activity Date/Time',
      5: 'Primary Activity Provider Code/Name',
      6: 'Origination Date/Time',
      7: 'Transcription Date/Time',
      8: 'Edit Date/Time',
      9: 'Originator Code/Name',
      10: 'Assigned Document Authenticator',
      11: 'Transcriptionist Code/Name',
      12: 'Unique Document Number',
      13: 'Parent Document Number',
      14: 'Placer Order Number',
      15: 'Filler Order Number',
      16: 'Unique Document File Name',
      17: 'Document Completion Status',
      18: 'Document Confidentiality Status',
      19: 'Document Availibility Status',
      20: 'Document Storage Status',
      21: 'Document Change Reason',
      22: 'Authentication Person, Time Stamp',
      23: 'Distributed Copies',
    },
    RXD: {
      1: 'Dispense Sub-ID Counter',
      2: 'Dispense Amount',
      3: 'Dispense Units',
      4: 'Dispense Drug',
      5: 'Dispense Number of Refills',
      6: 'Dispense Quantity',
      7: 'Dispensing Pharmacy',
      8: 'Dispensing Date/Time',
      9: 'Dispensing Provider',
    },
    NK1: {
      1: 'Set ID',
      2: 'Next of Kin Name',
      3: 'Relationship to Patient',
      4: 'Address',
      5: 'Phone Number',
      6: 'Business Phone Number',
      7: 'Contact Role',
      8: 'Start Date',
      9: 'End Date',
      10: 'Next of Kin Job Title',
      11: 'Next of Kin Job Code/Class',
      12: 'Next of Kin Employee Number',
      13: 'Organization Name - NK1',
      14: 'Martial Status',
      15: 'Administrative Sex',
      16: 'Date of Birth',
    },
    AL1: {
      1: 'Set ID',
      2: 'Allergy Type',
      3: 'Allergy Code',
      4: 'Allergy Severity',
      5: 'Allergy Reaction',
      6: 'Identification of Allergy',
    },
    PV1: {
      1: 'Set ID',
      2: 'Patient Class',
      3: 'Assigned Patient Location',
      4: 'Admission Type',
      5: 'Preadmit Number',
      6: 'Prior Patient Location',
      7: 'Attending Doctor',
      8: 'Referring Doctor',
      9: 'Consulting Doctor',
      10: 'Hospital Service',
      11: 'Temporary Location',
      12: 'Pre-admit Test Indicator',
      13: 'Re-admission Indicatior',
      14: 'Admit Source',
      15: 'Ambulatory Status',
      16: 'VIP Indicator',
      17: 'Admitting Doctor',
      18: 'Patient Type',
      19: 'Visit Number',
      20: 'Financial Class',
      21: 'Charge Price Indicator',
      22: 'Courtesy Code',
      23: 'Credit Rating',
      24: 'Contract Code',
      25: 'Contract Effective Date',
      26: 'Contract Amount',
      27: 'Contract Period',
      28: 'Interest Code',
      29: 'Transfer to Bad Debt Code',
      30: 'Transfer to Bad Debt Date',
      31: 'Bad Debt Agency Code',
      32: 'Bad Debt Transfer Amount',
      33: 'Bad Debt Recovery Amount',
      34: 'Delete Account Indicator',
      35: 'Delete Account Date',
      36: 'Discharge Disposition',
      37: 'Discharged to Location',
      38: 'Diet Type',
      39: 'Servicing Facility',
      40: 'Bed Status',
      41: 'Account Status',
      42: 'Pending Location',
      43: 'Prior Temporary Location',
      44: 'Admit Date/Time',
      45: 'Discharge Date/Time',
      46: 'Current Patient Balance',
      47: 'Total Charges',
      48: 'Total Adjustments',
      49: 'Total Payments',
      50: 'Alternate Visit ID',
      51: 'Visit Indicator',
      52: 'Other Healthcare Provider',
      53: 'Visit Protection Indicator',
    },
    CCR: {
      1: 'Set ID',
      2: 'Patient ID',
      3: 'Date/Time of Care',
      4: 'Type of Care',
      5: 'Provider ID',
      6: 'Care Description',
      7: 'Clinical Outcome',
      8: 'Follow-Up Plan',
      9: 'Allergy Information',
      10: 'Medications',
      11: 'Procedure Codes',
      12: 'Diagnosis Codes',
    },
    ALL: {
      1: 'Set ID',
      2: 'Allergen Code',
      3: 'Allergen Name',
      4: 'Reaction Type',
      5: 'Severity',
      6: 'Onset Date/Time',
      7: 'Allergy Status',
      8: 'Allergy Comments',
    },
    IN1: {
      1: 'Set ID',
      2: 'Insurance Plan ID',
      3: 'Insurance Company Name',
      4: 'Insurance Company Address',
      5: 'Insurance Co Contact Person',
      6: 'Insurance Company Phone Number',
      7: 'Group Number',
      8: 'Group Name',
      9: "Insured's Group Employ ID",
      10: "Insured's Group Emp Name",
      11: 'Plan Effective Date',
      12: 'Plan expiration date',
      13: 'Authorization Number',
      14: 'Plan type',
      15: 'Name of insured',
      16: "Insured's Relation to Patient",
      17: "Insured's Date of Birth",
      18: "Insured's Address",
      19: 'Assignment of Benefits',
      20: 'Coordination of Benefits',
      21: 'Coord Of Ben. Priority',
      22: 'Notice Of Admission Flag',
      23: 'Notice Of Admission Date',
      24: 'Report Of Eligibility Flag',
      25: 'Report Of Eligibility Date',
      26: 'RElease Information Code',
      27: 'Pre-Admit Cert (PAC)',
      28: 'Verification Date',
      29: 'Verification By',
      30: 'Type of Agreement Code',
      31: 'Billing Status',
      32: 'Lifetime Reserve Days',
      33: 'Delay Before L.R. Days',
      34: 'Company Plan Code',
      35: 'Policy Number',
      36: 'Policy Deductible',
      37: 'Policy Limit Amount',
      38: 'Policy Limit Days',
      39: 'Room Rate - Semi-Private',
      40: 'Room Rate - Private',
      41: "Insured's Employment Status",
      42: "Insured's Administrative Sex",
      43: "Insured's Employer's Address",
      44: 'Verification Status',
      45: 'Prior Insurance Company ID',
      46: 'Coverage Type',
      47: 'Handicap',
      48: "Insured's ID Number",
      49: 'Signature Code',
      50: 'Signature Code Date',
      51: "Insured's Birth Place",
      52: 'VIP Indicator',
    },
    ABS: {
      1: 'Discharge Care Level',
      2: 'Quotation of Care',
      3: 'Leave of Absence',
      4: 'Special Diet',
      5: 'Service',
      6: 'External Cause of Injury',
      7: 'Attending Doctor',
      8: 'Birth Weight',
      9: 'Duration of Pregnancy',
      10: 'Admission Condition',
      11: 'Living Will Code',
      12: 'Organ Donor Code',
      13: 'C-Section Indicator',
      14: 'Cestational Age',
    },
    ACC: {
      1: 'Accident Date/Time',
      2: 'Accident Code',
      3: 'Accident Location',
      4: 'Auto Accident State',
      5: 'Job Related Indicator',
      6: 'Death Indicator',
      7: 'Entered By',
      8: 'Accident Description',
      9: 'Bring-In Transport',
      10: 'Police Notified Indicator',
      11: 'Accident Address',
    },
    ADD: {
      1: 'Addendum Continuation Pointer',
    },
    AFF: {
      1: 'Set ID',
      2: 'Professional Organization',
      3: 'Professional Organization Address',
      4: 'Professional Organization Affiliation Date Range',
      5: 'Professional Affiliation Additional Information',
    },
    AIG: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Resource ID',
      4: 'Resource Type',
      5: 'Resource Group',
      6: 'Resource Quantity',
      7: 'Resource Quantity Units',
      8: 'Start Date/Time',
      9: 'Start Date/Time Offset',
      10: 'Start Date/Time Offset Units',
      11: 'Duration',
      12: 'Duration Units',
      13: 'Allow Substitution Code',
      14: 'Filler Status Code',
    },
    AIL: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Location Resource ID',
      4: 'Location Type',
      5: 'Location Group',
      6: 'Start Date/Time',
      7: 'Start Date/Time Offset',
      8: 'Start Date/Time Offset Units',
      9: 'Duration',
      10: 'Duration Units',
      11: 'Allow Substitution Code',
      12: 'Filler Status Code',
    },
    AIP: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Personnel Resource ID',
      4: 'Resource Type',
      5: 'Resource Group',
      6: 'Start Date/Time',
      7: 'Start Date/Time Offset',
      8: 'Start Date/Time Offset Units',
      9: 'Duration',
      10: 'Duration Units',
      11: 'Allow Substitution Code',
      12: 'Filler Status Code',
    },
    AIS: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Universal Service Identifier',
      4: 'Start Date/Time',
      5: 'Start Date/Time Offset',
      6: 'Start Date/Time Offset Units',
      7: 'Duration',
      8: 'Duration Units',
      9: 'Allow Substitution Code',
      10: 'Filler Status Code',
      11: 'Placer Supplemental Service Information',
      12: 'Filler Supplemental Service Information',
    },
    APR: {
      1: 'Time Selection Criteria',
      2: 'Resource Selection Criteria',
      3: 'Location Selection Criteria',
      4: 'Slot Spacing Criteria',
      5: 'Filler Override Criteria',
    },
    ARQ: {
      1: 'Placer Appointment ID',
      2: 'Filler Appointment ID',
      3: 'Occurrence Number',
      4: 'Placer Group Number',
      5: 'Schedule ID',
      6: 'Request Event Reason',
      7: 'Appointment Reason',
      8: 'Appointment Type',
      9: 'Appointment Duration',
      10: 'Appointment Duration Units',
      11: 'Requested Start Date/Time Range',
      12: 'Priority',
      13: 'Repeating Interval',
      14: 'Repeating Interval Duration',
      15: 'Placer Contact Person',
      16: 'Placer Contact Phone Number',
      17: 'Placer Contact Address',
      18: 'Placer Contact Location',
      19: 'Entered By Person',
      20: 'Entered By Phone Number',
      21: 'Entered By Location',
      22: 'Parent Placer Appointment ID',
      23: 'Parent Filler Appointment ID',
      24: 'Placer Order Number',
      25: 'Filler Order Number',
    },
    AUT: {
      1: 'Authorizing Payor, Plan ID',
      2: 'Authorizing Payor, Company ID',
      3: 'Authorizing Payor, Company Name',
      4: 'Authorization Effective Date',
      5: 'Authorization Expiration Date',
      6: 'Authorization Identifier',
      7: 'Reimbursement Limit',
      8: 'Requested Number of Treatments',
      9: 'Authorized Number of Treatments',
      10: 'Process Date',
    },
    BHS: {
      1: 'Batch Field Separator',
      2: 'Batch Encoding Characters',
      3: 'Batch Sending Application',
      4: 'Batch Sending Facility',
      5: 'Batch Receiving Application',
      6: 'Batch Receiving Facility',
      7: 'Batch Creation Date/Time',
      8: 'Batch Security',
      9: 'Batch Name/ID/Type',
      10: 'Batch Comment',
      11: 'Batch Control ID',
      12: 'Reference Batch Control ID',
    },
    BLC: {
      1: 'Blood Product Code',
      2: 'Blood Amount',
    },
    BLG: {
      1: 'When to Charge',
      2: 'Charge Type',
      3: 'Account ID',
      4: 'Charge Amount',
    },
    BPO: {
      1: 'Set ID',
      2: 'BP Universal Service Identifier',
      3: 'BP Prompt Code',
      4: 'BP Quantity',
      5: 'BP Amount',
      6: 'BP Units',
      7: 'BP Intended Use Date/Time',
      8: 'BP Intended Use Location',
      9: 'BP Indication for Use',
      10: 'BP Informed Consent Indicator',
      11: 'BP Special Requirements',
      12: 'BP Requested Date/Time',
      13: 'BP Collector Identifier',
      14: 'BP Processing Requirements',
    },
    BPX: {
      1: 'Set ID',
      2: 'BP Dispense Status',
      3: 'BP Status Change Date/Time',
      4: 'BP Blood Unit Identifier',
      5: 'BP Component',
      6: 'BP Donation Type',
      7: 'BP Component AB0/Rh',
      8: 'BP Blood Product Attributes',
      9: 'BP Unit Expiration Date/Time',
      10: 'BP Unit Quantity',
      11: 'BP Unit Amount',
      12: 'BP Unit Units',
      13: 'BP Unique ID',
      14: 'BP Method of Collection',
      15: 'BP Dispensing Provider',
      16: 'BP Dispensing Location',
      17: 'BP Dispense Date/Time',
      18: 'BP Dispensing Adherence',
      19: 'BP Dispensing Notes',
      20: 'BP Lot Number',
      21: 'BP Manufacturer',
    },
    BTS: {
      1: 'Batch Message Count',
      2: 'Batch Comment',
      3: 'Batch Totals',
    },
    BTX: {
      1: 'Set ID',
      2: 'BC Donation ID',
      3: 'BC Component',
      4: 'BC Blood Group',
      5: 'CP Transfusion/Disposition Status',
      6: 'CP Transfusion/Disposition Reason',
      7: 'CP Transfusion/Disposition Date/Time',
      8: 'CP Transfusion Provider',
      9: 'CP Transfusion Location',
      10: 'CP Adherence',
      11: 'CP Adverse Reaction Type',
      12: 'CP Transfusion Interrupt Reason',
      13: 'CP Transfusion Total Volume',
      14: 'CP Lot Number',
      15: 'CP Manufacturer',
    },
    CDM: {
      1: 'Primary Key Value',
      2: 'Charge Code Alias',
      3: 'Charge Description Short',
      4: 'Charge Description Long',
      5: 'Description Format Indicator',
      6: 'Department Code',
      7: 'Charge Category Service Section ID',
      8: 'Validity Selection Date',
      9: 'Charge Amount',
      10: 'Room Fee Indicator',
      11: 'G/L Account Number',
      12: 'Healthcare Service Location ID',
      13: 'Credit Rating',
    },
    CER: {
      1: 'Set ID',
      2: 'Certificate Type',
      3: 'Certificate ID',
      4: 'Certificate Authority',
      5: 'Certificate Signature',
      6: 'Certificate Issued Date',
      7: 'Certificate Expiry Date',
      8: 'Certificate Status',
      9: 'Certificate Subject',
      10: 'Certificate Subject Public Key',
      // ... continues up to index 31
    },
    CM0: {
      1: 'Set ID',
      2: 'Clinical Study ID',
      3: 'Clinical Study Phase ID',
      4: 'Clinical Study Description',
      5: 'Clinical Study Status',
    },
    CM1: {
      1: 'Set ID',
      2: 'Clinical Study Phase ID',
      3: 'Clinical Study Phase Description',
    },
    CM2: {
      1: 'Set ID',
      2: 'Scheduled Time Point ID',
      3: 'Scheduled Time Point Description',
      4: 'Events Scheduled',
    },
    CNS: {
      1: 'Starting Notification Reference Number',
      2: 'Ending Notification Reference Number',
      3: 'Starting Notification Date/Time',
      4: 'Ending Notification Date/Time',
    },
    CON: {
      1: 'Set ID',
      2: 'Consent Type',
      3: 'Consent Form ID',
      4: 'Consent Form Number',
      5: 'Consent Text',
      6: 'Consent State',
      7: 'Consent Discussion Date/Time',
      8: 'Consent Decision Date/Time',
      9: 'Consent Effective Date/Time',
      10: 'Consent End Date/Time',
      11: 'Subject Participation',
      12: 'Subject ID',
      13: 'Subject Name',
    },
    CSP: {
      1: 'Study Phase ID',
      2: 'Date/Time Study Phase Began',
      3: 'Date/Time Study Phase Ended',
      4: 'Study Phase Evaluability',
    },
    CSR: {
      1: 'Sponsor Study ID',
      2: 'Alternate Study ID',
      3: 'Institution Registering the Patient',
      4: 'Sponsor Patient ID',
      5: 'Alternate Patient ID - CSR',
      6: 'Date/Time Patient Registered',
      7: 'Person Registering Patient',
      8: 'Study Authorizer',
      9: 'Date/Time Patient Study Consent Signed',
      10: 'Patient Study Eligibility Status',
    },
    CSS: {
      1: 'Study Scheduled Time Point',
      2: 'Study Scheduled Patient Time Point',
      3: 'Study Quality Control Code',
    },
    CTD: {
      1: 'Contact Role',
      2: 'Contact Name',
      3: 'Contact Address',
      4: 'Contact Location',
      5: 'Contact Communication Information',
      6: 'Preferred Method of Contact',
      7: 'Contact Identifiers',
    },
    CTI: {
      1: 'Sponsor Study ID',
      2: 'Study Phase Identifier',
      3: 'Study Scheduled Time Point',
    },
    DB1: {
      1: 'Set ID',
      2: 'Disabled Person Code',
      3: 'Disabled Person Identifier',
      4: 'Disability Indicator',
      5: 'Disability Start Date',
      6: 'Disability End Date',
      7: 'Disability Return to Work Date',
      8: 'Disability Unable to Work Date',
    },
    DG1: {
      1: 'Set ID',
      2: 'Diagnosis Coding Method',
      3: 'Diagnosis Code',
      4: 'Diagnosis Description',
      5: 'Diagnosis Date/Time',
      6: 'Diagnosis Type',
      7: 'Major Diagnostic Category',
      8: 'Diagnostic Related Group',
      9: 'DRG Approval Indicator',
      10: 'DRG Grouper Review Code',
      11: 'Outlier Type',
      12: 'Outlier Days',
      13: 'Outlier Cost',
      14: 'Grouper Version and Type',
      15: 'Diagnosis Priority',
      16: 'Diagnosing Clinician',
      17: 'Diagnosis Classification',
      18: 'Confidential Indicator',
      19: 'Attestation Date/Time',
    },
    DRG: {
      1: 'Diagnostic Related Group',
      2: 'DRG Assigned Date/Time',
      3: 'DRG Approval Indicator',
      4: 'DRG Grouper Review Code',
      5: 'Outlier Type',
      6: 'Outlier Days',
      7: 'Outlier Cost',
      8: 'DRG Payor',
      9: 'Outlier Reimbursement',
      10: 'Confidential Indicator',
      11: 'DRG Transfer Type',
    },
    DSC: {
      1: 'Continuation Pointer',
      2: 'Continuation Style',
    },
    DSP: {
      1: 'Set ID',
      2: 'Display Level',
      3: 'Data Line',
      4: 'Logical Break',
      5: 'Result ID',
    },
  };

  return descriptions[segmentType]?.[fieldIndex] ?? 'Field Description';
}
