/** Placeholder used so escaped \F\ in field values don't break segment split. */
const ESCAPED_FIELD_PLACEHOLDER = '\u0001';

/**
 * Split a segment line by field separator (|), respecting HL7 escape \F\ (literal pipe in value).
 * @param {string} segment - One segment line (e.g. "PID|1||123^abc")
 * @returns {string[]} [type, field1, field2, ...]
 */
function splitSegmentFields(segment) {
  const withPlaceholder = segment.replace(/\\F\\/g, ESCAPED_FIELD_PLACEHOLDER);
  const parts = withPlaceholder.split('|');
  return parts.map((value) => value.replace(new RegExp(ESCAPED_FIELD_PLACEHOLDER, 'g'), '|'));
}

/**
 * @param {string} message
 * @returns {{ type: string; raw: string; fields: Array<{ fieldNumber: number; value: string; description: string }> }[]}
 */
export function parseHL7Message(rawMessage) {
  if (!rawMessage) return [];

  const lines = rawMessage
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean);

  if (!lines.length) return [];

  // --- Extract separators from MSH ---
  const mshLine = lines[0];
  const fieldSep = mshLine[3];
  const encodingChars = mshLine.substring(4, 8);

  const separators = {
    field: fieldSep,
    component: encodingChars[0],
    repetition: encodingChars[1],
    escape: encodingChars[2],
    subcomponent: encodingChars[3],
  };

  // --- Parse segments ---
  return lines.map((line) => {
    const segmentType = line.substring(0, 3);
    const rawFields = line.split(separators.field);

    if (segmentType === 'MSH') {
      // MSH-1 = field separator (char after "MSH"); MSH-2 = encoding chars (4 chars); rest align with HL7 field numbers 3+
      const mshFieldSep = line[3];
      const mshEncoding = line.substring(4, 8);

      const fields = [
        {
          raw: mshFieldSep,
          fieldNumber: 1,
          parsed: atomicParsed(mshFieldSep),
        },
        {
          raw: mshEncoding,
          fieldNumber: 2,
          parsed: atomicParsed(mshEncoding),
        },
        ...rawFields.slice(2).map((value, index) => ({
          raw: value,
          fieldNumber: index + 3,
          parsed: parseField(value, separators),
        })),
      ];

      return {
        type: segmentType,
        separators,
        fields,
      };
    }

    const fields = rawFields.slice(1).map((value, index) => ({
      raw: value,
      fieldNumber: index + 1,
      parsed: parseField(value, separators),
    }));

    return {
      type: segmentType,
      separators,
      fields,
    };
  });
}

function parseField(value, sep) {
  if (!value) return [];

  return value.split(sep.repetition).map((repeat) =>
    repeat.split(sep.component).map((component) =>
      component.split(sep.subcomponent)
    )
  );
}

/** One repetition, one component, one subcomponent — avoids splitting MSH-2 on ^ ~ \\ & */
function atomicParsed(value) {
  return [[[value]]];
}

/**
 * HL7 version 2.5.1 field descriptions.
 * @param {string} segmentType
 * @param {number} fieldIndex - HL7 field number (1-based)
 * @returns {string}
 */
export function getFieldDescription(segmentType, fieldIndex) {
  const descriptions = {
 
    ABS: {
      1: 'Discharge Care Provider',
      2: 'Transfer Medical Service Code',
      3: 'Severity of Illness Code',
      4: 'Date/Time of Attestation',
      5: 'Attested By',
      6: 'Triage Code',
      7: 'Abstract Completion Date/Time',
      8: 'Abstracted By',
      9: 'Case Category Code',
      10: 'Caesarian Section Indicator',
      11: 'Gestation Category Code',
      12: 'Gestation Period - Weeks',
      13: 'Newborn Code',
      14: 'Stillborn Indicator',
    },
    ACC: {
      1: 'Accident Date/Time',
      2: 'Accident Code',
      3: 'Accident Location',
      4: 'Auto Accident State',
      5: 'Accident Job Related Indicator',
      6: 'Accident Death Indicator',
      7: 'Entered By',
      8: 'Accident Description',
      9: 'Brought In By',
      10: 'Police Notified Indicator',
      11: 'Accident Address',
    },
    ADD: {
      1: 'Addendum Continuation Pointer',
    },
    AFF: {
      1: 'Set ID',
      2: 'Professional Organization',
      3: 'Professional Organization Address',
      4: 'Professional Organization Affiliation Date Range',
      5: 'Professional Affiliation Additional Information',
    },
    AIG: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Resource ID',
      4: 'Resource Type',
      5: 'Resource Group',
      6: 'Resource Quantity',
      7: 'Resource Quantity Units',
      8: 'Start Date/Time',
      9: 'Start Date/Time Offset',
      10: 'Start Date/Time Offset Units',
      11: 'Duration',
      12: 'Duration Units',
      13: 'Allow Substitution Code',
      14: 'Filler Status Code',
    },
    AIL: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Location Resource ID',
      4: 'Location Type',
      5: 'Location Group',
      6: 'Start Date/Time',
      7: 'Start Date/Time Offset',
      8: 'Start Date/Time Offset Units',
      9: 'Duration',
      10: 'Duration Units',
      11: 'Allow Substitution Code',
      12: 'Filler Status Code',
    },
    AIP: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Personnel Resource ID',
      4: 'Resource Type',
      5: 'Resource Group',
      6: 'Start Date/Time',
      7: 'Start Date/Time Offset',
      8: 'Start Date/Time Offset Units',
      9: 'Duration',
      10: 'Duration Units',
      11: 'Allow Substitution Code',
      12: 'Filler Status Code',
    },
    AIS: {
      1: 'Set ID',
      2: 'Segment Action Code',
      3: 'Universal Service Identifier',
      4: 'Start Date/Time',
      5: 'Start Date/Time Offset',
      6: 'Start Date/Time Offset Units',
      7: 'Duration',
      8: 'Duration Units',
      9: 'Allow Substitution Code',
      10: 'Filler Status Code',
      11: 'Placer Supplemental Service Information',
      12: 'Filler Supplemental Service Information',
    },
    AL1: {
      1: 'Set ID',
      2: 'Allergy Type Code',
      3: 'Allergy Code/Mnemonic/Description',
      4: 'Allergy Severity Code',
      5: 'Allergy Reaction Code',
      6: 'Identification Date',
    },
    APR: {
      1: 'Time Selection Criteria',
      2: 'Resource Selection Criteria',
      3: 'Location Selection Criteria',
      4: 'Slot Spacing Criteria',
      5: 'Filler Override Criteria',
    },
    ARQ: {
      1: 'Placer Appointment ID',
      2: 'Filler Appointment ID',
      3: 'Occurrence Number',
      4: 'Placer Group Number',
      5: 'Schedule ID',
      6: 'Request Event Reason',
      7: 'Appointment Reason',
      8: 'Appointment Type',
      9: 'Appointment Duration',
      10: 'Appointment Duration Units',
      11: 'Requested Start Date/Time Range',
      12: 'Priority-ARQ',
      13: 'Repeating Interval',
      14: 'Repeating Interval Duration',
      15: 'Placer Contact Person',
      16: 'Placer Contact Phone Number',
      17: 'Placer Contact Address',
      18: 'Placer Contact Location',
      19: 'Entered By Person',
      20: 'Entered By Phone Number',
      21: 'Entered By Location',
      22: 'Parent Placer Appointment ID',
      23: 'Parent Filler Appointment ID',
      24: 'Placer Order Number',
      25: 'Filler Order Number',
    },
    AUT: {
      1: 'Authorizing Payor, Plan ID',
      2: 'Authorizing Payor, Company ID',
      3: 'Authorizing Payor, Company Name',
      4: 'Authorization Effective Date',
      5: 'Authorization Expiration Date',
      6: 'Authorization Identifier',
      7: 'Reimbursement Limit',
      8: 'Requested Number of Treatments',
      9: 'Authorized Number of Treatments',
      10: 'Process Date',
    },
    BHS: {
      1: 'Batch Field Separator',
      2: 'Batch Encoding Characters',
      3: 'Batch Sending Application',
      4: 'Batch Sending Facility',
      5: 'Batch Receiving Application',
      6: 'Batch Receiving Facility',
      7: 'Batch Creation Date/Time',
      8: 'Batch Security',
      9: 'Batch Name/ID/Type',
      10: 'Batch Comment',
      11: 'Batch Control ID',
      12: 'Reference Batch Control ID',
    },
    BLC: {
      1: 'Blood Product Code',
      2: 'Blood Amount',
    },
    BLG: {
      1: 'When to Charge',
      2: 'Charge Type',
      3: 'Account ID',
      4: 'Charge Type Reason',
    },
    BPO: {
      1: 'Set ID',
      2: 'BP Universal Service ID',
      3: 'BP Processing Requirements',
      4: 'BP Quantity',
      5: 'BP Amount',
      6: 'BP Units',
      7: 'BP Intended Use Date/Time',
      8: 'BP Intended Dispense From Location',
      9: 'BP Intended Dispense From Address',
      10: 'BP Requested Dispense Date/Time',
      11: 'BP Requested Dispense To Location',
      12: 'BP Requested Dispense To Address',
      13: 'BP Indication for Use',
      14: 'BP Informed Consent Indicator',
    }, 
    BPX: {
      1: 'Set ID',
      2: 'BP Dispense Status',
      3: 'BP Status',
      4: 'BP Date/Time of Status',
      5: 'BC Donation ID',
      6: 'BC Component',
      7: 'BC Donation Type / Intended Use',
      8: 'CP Commercial Product',
      9: 'CP Manufacturer',
      10: 'CP Lot Number',
      11: 'BP Blood Group',
      12: 'BC Special Testing',
      13: 'BP Expiration Date/Time',
      14: 'BP Quantity',
      15: 'BP Amount',
      16: 'BP Units',
      17: 'BP Unique ID',
      18: 'BP Actual Dispensed To Location',
      19: 'BP Actual Dispensed To Address',
      20: 'BP Dispensed to Receiver',
      21: 'BP Dispensing Individual',
    },
    BTS: {
      1: 'Batch Message Count',
      2: 'Batch Comment',
      3: 'Batch Totals',
    },
    BTX: {
      1: 'Set ID',
      2: 'BC Donation ID',
      3: 'BC Component',
      4: 'BC Blood Group',
      5: 'CP Commercial Product',
      6: 'CP Manufacturer',
      7: 'CP Lot Number',
      8: 'BP Quantity',
      9: 'BP Amount',
      10: 'BP Units',
      11: 'BP Transfusion/Disposition Status',
      12: 'BP Message Status',
      13: 'BP Date/Time of Status',
      14: 'BP Administrator',
      15: 'BP Verifier',
      16: 'BP Transfusion Start Date/Time of Status',
      17: 'BP Transfusion End Date/Time of Status',
      18: 'BP Adverse Reaction Type',
      19: 'BP Transfusion Interrupted Reason',
    },
    CDM: {
      1: 'Primary Key Value',
      2: 'Charge Code Alias',
      3: 'Charge Description Short',
      4: 'Charge Description Long',
      5: 'Description Override Indicator',
      6: 'Exploding Charges',
      7: 'Procedure Code',
      8: 'Active/Inactive Flag',
      9: 'Inventory Number',
      10: 'Resource Load',
      11: 'Contract Number',
      12: 'Contract Organization',
      13: 'Room Fee Indicator',
    },
    CER: {
      1: 'Set ID',
      2: 'Serial Number',
      3: 'Version',
      4: 'Granting Authority',
      5: 'Issuing Authority',
      6: 'Signature of Issuing Authority',
      7: 'Granting Country',
      8: 'Granting State/Province',
      9: 'Granting County/Parish',
      10: 'Certificate Type',
      11: 'Certificate Domain',
      12: 'Subject ID',
      13: 'Subject Name',
      14: 'Subject Directory Attribute Extension (Health Professional Data)',
      15: 'Subject Public Key Info',
      16: 'Authority Key Identifier',
      17: 'Basic Constraint',
      18: 'CRL Distribution Point',
      19: 'Jurisdiction Country',
      20: 'Jurisdiction State/Province',
      21: 'Jurisdiction County/Parish',
      22: 'Jurisdiction Breadth',
      23: 'Granting Date',
      24: 'Issuing Date',
      25: 'Activation Date',
      26: 'Inactivation Date',
      27: 'Expiration Date',
      28: 'Renewal Date',
      29: 'Revocation Date',
      30: 'Revocation Reason Code',
      31: 'Certificate Status',
    },
    CM0: {
      1: 'Set ID',
      2: 'Sponsor Study ID',
      3: 'Alternate Study ID',
      4: 'Title of Study',
      5: 'Chairman of Study',
      6: 'Last IRB Approval Date',
      7: 'Total Accrual to Date',
      8: 'Last Accrual Date',
      9: 'Contact for Study',
      10: "Contact's Telephone Number",
      11: "Contact's Address",
    },
    CM1: {
      1: 'Set ID',
      2: 'Study Phase Identifier',
      3: 'Description of Study Phase',
    },
    CM2: {
      1: 'Set ID',
      2: 'Scheduled Time Point',
      3: 'Description of Time Point',
      4: 'Events Scheduled This Time Point',
    },
    CNS: {
      1: 'Starting Notification Reference Number',
      2: 'Ending Notification Reference Number',
      3: 'Starting Notification Date/Time',
      4: 'Ending Notification Date/Time',
      5: 'Starting Notification Code',
      6: 'Ending Notification Code',
    },
    CON: {
      1: 'Set ID',
      2: 'Consent Type',
      3: 'Consent Form ID',
      4: 'Consent Form Number',
      5: 'Consent Text',
      6: 'Subject-specific Consent Text',
      7: 'Consent Background',
      8: 'Subject-specific Consent Background',
      9: 'Consenter-imposed limitations',
      10: 'Consent Mode',
      11: 'Consent Status',
      12: 'Consent Discussion Date/Time',
      13: 'Consent Decision Date/Time',
      14: 'Consent Effective Date/Time',
      15: 'Consent End Date/Time',
      16: 'Subject Competence Indicator',
      17: 'Translator Assistance Indicator',
      18: 'Language Translated To',
      19: 'Informational Material Supplied Indicator',
      20: 'Consent Bypass Reason',
      21: 'Consent Disclosure Level',
      22: 'Consent Non-disclosure Reason',
      23: 'Non-subject Consenter Reason',
      24: 'Consenter ID',
      25: 'Relationship to Subject Table',
    },
    CSP: {
      1: 'Study Phase Identifier',
      2: 'Date/Time Study Phase Began',
      3: 'Date/Time Study Phase Ended',
      4: 'Study Phase Evaluability',
    },
    CSR: {
      1: 'Sponsor Study ID',
      2: 'Alternate Study ID',
      3: 'Institution Registering the Patient',
      4: 'Sponsor Patient ID',
      5: 'Alternate Patient ID - CSR',
      6: 'Date/Time Of Patient Study Registration',
      7: 'Person Performing Study Registration',
      8: 'Study Authorizing Provider',
      9: 'Date/time Patient Study Consent Signed',
      10: 'Patient Study Eligibility Status',
      11: 'Study Randomization Date/time',
      12: 'Randomized Study Arm',
      13: 'Stratum for Study Randomization',
      14: 'Patient Evaluability Status',
      15: 'Date/time Ended Study',
      16: 'Reason Ended Study',
    },
    CSS: {
      1: 'Study Scheduled Time Point',
      2: 'Study Scheduled Patient Time Point',
      3: 'Study Quality Control Codes',
    },
    CTD: {
      1: 'Contact Role',
      2: 'Contact Name',
      3: 'Contact Address',
      4: 'Contact Location',
      5: 'Contact Communication Information',
      6: 'Preferred Method of Contact',
      7: 'Contact Identifiers',
    },
    CTI: {
      1: 'Sponsor Study ID',
      2: 'Study Phase Identifier',
      3: 'Study Scheduled Time Point',
    },
    DB1: {
      1: 'Set ID - DB1',
      2: 'Disabled Person Code',
      3: 'Disabled Person Identifier',
      4: 'Disability Indicator',
      5: 'Disability Start Date',
      6: 'Disability End Date',
      7: 'Disability Return to Work Date',
      8: 'Disability Unable to Work Date',
    },
    DG1: {
      1: 'Set ID',
      2: 'Diagnosis Coding Method',
      3: 'Diagnosis Code',
      4: 'Diagnosis Description',
      5: 'Diagnosis Date/Time',
      6: 'Diagnosis Type',
      7: 'Major Diagnostic Category',
      8: 'Diagnostic Related Group',
      9: 'DRG Approval Indicator',
      10: 'DRG Grouper Review Code',
      11: 'Outlier Type',
      12: 'Outlier Days',
      13: 'Outlier Cost',
      14: 'Grouper Version And Type',
      15: 'Diagnosis Priority',
      16: 'Diagnosing Clinician',
      17: 'Diagnosis Classification',
      18: 'Confidential Indicator',
      19: 'Attestation Date/Time',
      20: 'Diagnosis Identifier',
      21: 'Diagnosis Action Code',
    },
    DRG: {
      1: 'Diagnostic Related Group',
      2: 'DRG Assigned Date/Time',
      3: 'DRG Approval Indicator',
      4: 'DRG Grouper Review Code',
      5: 'Outlier Type',
      6: 'Outlier Days',
      7: 'Outlier Cost',
      8: 'DRG Payor',
      9: 'Outlier Reimbursement',
      10: 'Confidential Indicator',
      11: 'DRG Transfer Type',
    },
    DSC: {
      1: 'Continuation Pointer',
      2: 'Continuation Style',
    },
    DSP: {
      1: 'Set ID',
      2: 'Display Level',
      3: 'Data Line',
      4: 'Logical Break Point',
      5: 'Result ID',
    },
    ECD: {
      1: 'Reference Command Number',
      2: 'Remote Control Command',
      3: 'Response Required',
      4: 'Requested Completion Time',
      5: 'Parameters',
    },
    ECR: {
      1: 'Command Response',
      2: 'Date/Time Completed',
      3: 'Command Response Parameters',
    },
    EDU: {
      1: 'Set ID',
      2: 'Academic Degree',
      3: 'Academic Degree Program Date Range',
      4: 'Academic Degree Program Participation Date Range',
      5: 'Academic Degree Granted Date',
      6: 'School',
      7: 'School Type Code',
      8: 'School Address',
      9: 'Major Field of Study',
    },
    EQL: {
      1: 'Query Tag',
      2: 'Query/Response Format Code',
      3: 'EQL Query Name',
      4: 'EQL Query Statement',
    },
    EQP: {
      1: 'Event type',
      2: 'File Name',
      3: 'Start Date/Time',
      4: 'End Date/Time',
      5: 'Transaction Data',
    },
    EQU: {
      1: 'Equipment Instance Identifier',
      2: 'Event Date/Time',
      3: 'Equipment State',
      4: 'Local/Remote Control State',
      5: 'Alert Level',
    },
    ERQ: {
      1: 'Query Tag',
      2: 'Event Identifier',
      3: 'Input Parameter List',
    },
    ERR: {
      1: 'Error Code and Location',
      2: 'Error Location',
      3: 'HL7 Error Code',
      4: 'Severity',
      5: 'Application Error Code',
      6: 'Application Error Parameter',
      7: 'Diagnostic Information',
      8: 'User Message',
      9: 'Inform Person Indicator',
      10: 'Override Type',
      11: 'Override Reason Code',
      12: 'Help Desk Contact Point',
    },
    EVN: {
      1: 'Event Type Code',
      2: 'Recorded Date/Time',
      3: 'Date/Time Planned Event',
      4: 'Event Reason Code',
      5: 'Operator ID',
      6: 'Event Occurred',
    },
    FAC: {
      1: 'Facility ID',
      2: 'Facility Type',
      3: 'Facility Address',
      4: 'Facility Telecommunication',
      5: 'Contact Person',
      6: 'Contact Title',
      7: 'Contact Address',
      8: 'Contact Telecommunication',
      9: 'Signature Authority',
      10: 'Signature Authority Title',
      11: 'Signature Authority Address',
      12: 'Signature Authority Telecommunication',
    },
    FHS: {
      1: 'File Field Separator',
      2: 'File Encoding Characters',
      3: 'File Sending Application',
      4: 'File Sending Facility',
      5: 'File Receiving Application',
      6: 'File Receiving Facility',
      7: 'File Creation Date/Time',
      8: 'File Security',
      9: 'File Name/ID',
      10: 'File Header Comment',
      11: 'File Control ID',
      12: 'Reference File Control ID',
    },
    FT1: {
      1: 'Set ID',
      2: 'Transaction ID',
      3: 'Transaction Batch ID',
      4: 'Transaction Date',
      5: 'Transaction Posting Date',
      6: 'Transaction Type',
      7: 'Transaction Code',
      8: 'Transaction Description',
      9: 'Transaction Description - Alt',
      10: 'Transaction Quantity',
      11: 'Transaction Amount - Extended',
      12: 'Transaction Amount - Unit',
      13: 'Department Code',
      14: 'Insurance Plan ID',
      15: 'Insurance Amount',
      16: 'Assigned Patient Location',
      17: 'Fee Schedule',
      18: 'Patient Type',
      19: 'Diagnosis Code - FT1',
      20: 'Performed By Code',
      21: 'Ordered By Code',
      22: 'Unit Cost',
      23: 'Filler Order Number',
      24: 'Entered By Code',
      25: 'Procedure Code',
      26: 'Procedure Code Modifier',
      27: 'Advanced Beneficiary Notice Code',
      28: 'Medically Necessary Duplicate Procedure Reason.',
      29: 'NDC Code',
      30: 'Payment Reference ID',
      31: 'Transaction Reference Key',
    },
    FTS: {
      1: 'File Batch Count',
      2: 'File Trailer Comment',
    },
    GOL: {
      1: 'Action Code',
      2: 'Action Date/Time',
      3: 'Goal ID',
      4: 'Goal Instance ID',
      5: 'Episode of Care ID',
      6: 'Goal List Priority',
      7: 'Goal Established Date/Time',
      8: 'Expected Goal Achieve Date/Time',
      9: 'Goal Classification',
      10: 'Goal Management Discipline',
      11: 'Current Goal Review Status',
      12: 'Current Goal Review Date/Time',
      13: 'Next Goal Review Date/Time',
      14: 'Previous Goal Review Date/Time',
      15: 'Goal Review Interval',
      16: 'Goal Evaluation',
      17: 'Goal Evaluation Comment',
      18: 'Goal Life Cycle Status',
      19: 'Goal Life Cycle Status Date/Time',
      20: 'Goal Target Type',
      21: 'Goal Target Name',
    },
    GP1: {
      1: 'Type of Bill Code',
      2: 'Revenue Code',
      3: 'Overall Claim Disposition Code',
      4: 'OCE Edits per Visit Code',
      5: 'Outlier Cost',
    },
    GP2: {
      1: 'Revenue Code',
      2: 'Number of Service Units',
      3: 'Charge',
      4: 'Reimbursement Action Code',
      5: 'Denial or Rejection Code',
      6: 'OCE Edit Code',
      7: 'Ambulatory Payment Classification Code',
      8: 'Modifier Edit Code',
      9: 'Payment Adjustment Code',
      10: 'Packaging Status Code',
      11: 'Expected CMS Payment Amount',
      12: 'Reimbursement Type Code',
      13: 'Co-Pay Amount',
      14: 'Pay Rate per Service Unit',
    },
    GT1: {
      1: 'Set ID',
      2: 'Guarantor Number',
      3: 'Guarantor Name',
      4: 'Guarantor Spouse Name',
      5: 'Guarantor Address',
      6: 'Guarantor Ph Num - Home',
      7: 'Guarantor Ph Num - Business',
      8: 'Guarantor Date/Time Of Birth',
      9: 'Guarantor Administrative Sex',
      10: 'Guarantor Type',
      11: 'Guarantor Relationship',
      12: 'Guarantor SSN',
      13: 'Guarantor Date - Begin',
      14: 'Guarantor Date - End',
      15: 'Guarantor Priority',
      16: 'Guarantor Employer Name',
      17: 'Guarantor Employer Address',
      18: 'Guarantor Employer Phone Number',
      19: 'Guarantor Employee ID Number',
      20: 'Guarantor Employment Status',
      21: 'Guarantor Organization Name',
      22: 'Guarantor Billing Hold Flag',
      23: 'Guarantor Credit Rating Code',
      24: 'Guarantor Death Date And Time',
      25: 'Guarantor Death Flag',
      26: 'Guarantor Charge Adjustment Code',
      27: 'Guarantor Household Annual Income',
      28: 'Guarantor Household Size',
      29: 'Guarantor Employer ID Number',
      30: 'Guarantor Marital Status Code',
      31: 'Guarantor Hire Effective Date',
      32: 'Employment Stop Date',
      33: 'Living Dependency',
      34: 'Ambulatory Status',
      35: 'Citizenship',
      36: 'Primary Language',
      37: 'Living Arrangement',
      38: 'Publicity Code',
      39: 'Protection Indicator',
      40: 'Student Indicator',
      41: 'Religion',
      42: "Mother's Maiden Name",
      43: 'Nationality',
      44: 'Ethnic Group',
      45: "Contact Person's Name",
      46: "Contact Person's Telephone Number",
      47: 'Contact Reason',
      48: 'Contact Relationship',
      49: 'Job Title',
      50: 'Job Code/Class',
      51: "Guarantor Employer's Organization Name",
      52: 'Handicap',
      53: 'Job Status',
      54: 'Guarantor Financial Class',
      55: 'Guarantor Race',
      56: 'Guarantor Birth Place',
      57: 'VIP Indicator',
    },
    IAM: {
      1: 'Set ID',
      2: 'Allergen Type Code',
      3: 'Allergen Code/Mnemonic/Description',
      4: 'Allergy Severity Code',
      5: 'Allergy Reaction Code',
      6: 'Allergy Action Code',
      7: 'Allergy Unique Identifier',
      8: 'Action Reason',
      9: 'Sensitivity to Causative Agent Code',
      10: 'Allergen Group Code/Mnemonic/Description',
      11: 'Onset Date',
      12: 'Onset Date Text',
      13: 'Reported Date/Time',
      14: 'Reported By',
      15: 'Relationship to Patient Code',
      16: 'Alert Device Code',
      17: 'Allergy Clinical Status Code',
      18: 'Statused by Person',
      19: 'Statused by Organization',
      20: 'Statused at Date/Time',
    },
    IIM: {
      1: 'Primary Key Value',
      2: 'Service Item Code',
      3: 'Inventory Lot Number',
      4: 'Inventory Expiration Date',
      5: 'Inventory Manufacturer Name',
      6: 'Inventory Location',
      7: 'Inventory Received Date',
      8: 'Inventory Received Quantity',
      9: 'Inventory Received Quantity Unit',
      10: 'Inventory Received Item Cost',
      11: 'Inventory On Hand Date',
      12: 'Inventory On Hand Quantity',
      13: 'Inventory On Hand Quantity Unit',
      14: 'Procedure Code',
      15: 'Procedure Code Modifier',
    },
    IN1: {
      1: 'Set ID',
      2: 'Insurance Plan ID',
      3: 'Insurance Company ID',
      4: 'Insurance Company Name',
      5: 'Insurance Company Address',
      6: 'Insurance Co Contact Person',
      7: 'Insurance Co Phone Number',
      8: 'Group Number',
      9: 'Group Name',
      10: "Insured's Group Emp ID",
      11: "Insured's Group Emp Name",
      12: 'Plan Effective Date',
      13: 'Plan Expiration Date',
      14: 'Authorization Information',
      15: 'Plan Type',
      16: 'Name Of Insured',
      17: "Insured's Relationship To Patient",
      18: "Insured's Date Of Birth",
      19: "Insured's Address",
      20: 'Assignment Of Benefits',
      21: 'Coordination Of Benefits',
      22: 'Coord Of Ben. Priority',
      23: 'Notice Of Admission Flag',
      24: 'Notice Of Admission Date',
      25: 'Report Of Eligibility Flag',
      26: 'Report Of Eligibility Date',
      27: 'Release Information Code',
      28: 'Pre-Admit Cert (PAC)',
      29: 'Verification Date/Time',
      30: 'Verification By',
      31: 'Type Of Agreement Code',
      32: 'Billing Status',
      33: 'Lifetime Reserve Days',
      34: 'Delay Before L.R. Day',
      35: 'Company Plan Code',
      36: 'Policy Number',
      37: 'Policy Deductible',
      38: 'Policy Limit - Amount',
      39: 'Policy Limit - Days',
      40: 'Room Rate - Semi-Private',
      41: 'Room Rate - Private',
      42: "Insured's Employment Status",
      43: "Insured's Administrative Sex",
      44: "Insured's Employer's Address",
      45: 'Verification Status',
      46: 'Prior Insurance Plan ID',
      47: 'Coverage Type',
      48: 'Handicap',
      49: "Insured's ID Number",
      50: 'Signature Code',
      51: 'Signature Code Date',
      52: "Insured's Birth Place",
      53: 'VIP Indicator',
    },
    IN2: {
      1: "Insured's Employee ID",
      2: "Insured's Social Security Number",
      3: "Insured's Employer's Name and ID",
      4: 'Employer Information Data',
      5: 'Mail Claim Party',
      6: 'Medicare Health Ins Card Number',
      7: 'Medicaid Case Name',
      8: 'Medicaid Case Number',
      9: 'Military Sponsor Name',
      10: 'Military ID Number',
      11: 'Dependent Of Military Recipient',
      12: 'Military Organization',
      13: 'Military Station',
      14: 'Military Service',
      15: 'Military Rank/Grade',
      16: 'Military Status',
      17: 'Military Retire Date',
      18: 'Military Non-Avail Cert On File',
      19: 'Baby Coverage',
      20: 'Combine Baby Bill',
      21: 'Blood Deductible',
      22: 'Special Coverage Approval Name',
      23: 'Special Coverage Approval Title',
      24: 'Non-Covered Insurance Code',
      25: 'Payor ID',
      26: 'Payor Subscriber ID',
      27: 'Eligibility Source',
      28: 'Room Coverage Type/Amount',
      29: 'Policy Type/Amount',
      30: 'Daily Deductible',
      31: 'Living Dependency',
      32: 'Ambulatory Status',
      33: 'Citizenship',
      34: 'Primary Language',
      35: 'Living Arrangement',
      36: 'Publicity Code',
      37: 'Protection Indicator',
      38: 'Student Indicator',
      39: 'Religion',
      40: "Mother's Maiden Name",
      41: 'Nationality',
      42: 'Ethnic Group',
      43: 'Marital Status',
      44: "Insured's Employment Start Date",
      45: 'Employment Stop Date',
      46: 'Job Title',
      47: 'Job Code/Class',
      48: 'Job Status',
      49: 'Employer Contact Person Name',
      50: 'Employer Contact Person Phone Number',
      51: 'Employer Contact Reason',
      52: "Insured's Contact Person's Name",
      53: "Insured's Contact Person Phone Number",
      54: "Insured's Contact Person Reason",
      55: 'Relationship to the Patient Start Date',
      56: 'Relationship to the Patient Stop Date',
      57: 'Insurance Co. Contact Reason',
      58: 'Insurance Co Contact Phone Number',
      59: 'Policy Scope',
      60: 'Policy Source',
      61: 'Patient Member Number',
    },
    IN3: {
      1: 'Set ID',
      2: 'Certification Number',
      3: 'Certified By',
      4: 'Certification Required',
      5: 'Penalty',
      6: 'Certification Date/Time',
      7: 'Certification Modify Date/Time',
      8: 'Operator',
      9: 'Certification Begin Date',
      10: 'Certification End Date',
      11: 'Days',
      12: 'Non-Concur Code/Description',
      13: 'Non-Concur Effective Date/Time',
      14: 'Physician Reviewer',
      15: 'Certification Contact',
      16: 'Certification Contact Phone Number',
      17: 'Appeal Reason',
      18: 'Certification Agency',
      19: 'Certification Agency Phone Number',
      20: 'Pre-Certification Requirement',
      21: 'Case Manager',
      22: 'Second Opinion Date',
      23: 'Second Opinion Status',
      24: 'Second Opinion Documentation Received',
      25: 'Second Opinion Physician',
    },
    INV: {
      1: 'Substance Identifier',
      2: 'Substance Status',
      3: 'Substance Type',
      4: 'Inventory Container Identifier',
      5: 'Container Carrier Identifier',
      6: 'Position on Carrier',
      7: 'Initial Quantity',
      8: 'Current Quantity',
      9: 'Available Quantity',
      10: 'Consumption Quantity',
      11: 'Quantity Units',
      12: 'Expiration Date/Time',
      13: 'First Used Date/Time',
      14: 'On Board Stability Duration',
      15: 'Test/Fluid Identifier(s)',
      16: 'Manufacturer Lot Number',
      17: 'Manufacturer Identifier',
      18: 'Supplier Identifier',
      19: 'On Board Stability Time',
      20: 'Target Value',
    },
    IPC: {
      1: 'Accession Identifier',
      2: 'Requested Procedure ID',
      3: 'Study Instance UID',
      4: 'Scheduled Procedure Step ID',
      5: 'Modality',
      6: 'Protocol Code',
      7: 'Scheduled Station Name',
      8: 'Scheduled Procedure Step Location',
      9: 'Scheduled AE Title',
    },
    ISD: {
      1: 'Reference Interaction Number (unique identifier)',
      2: 'Interaction Type Identifier',
      3: 'Interaction Active State',
    },
    LAN: {
      1: 'Set ID',
      2: 'Language Code',
      3: 'Language Ability Code',
      4: 'Language Proficiency Code',
    },
    LCC: {
      1: 'Primary Key Value',
      2: 'Location Department',
      3: 'Accommodation Type',
      4: 'Charge Code',
    },
    LCH: {
      1: 'Primary Key Value',
      2: 'Segment Action Code',
      3: 'Segment Unique Key',
      4: 'Location Characteristic ID',
      5: 'Location Characteristic Value',
    },
    LDP: {
      1: 'Primary Key Value',
      2: 'Location Department',
      3: 'Location Service',
      4: 'Specialty Type',
      5: 'Valid Patient Classes',
      6: 'Active/Inactive Flag',
      7: 'Activation Date',
      8: 'Inactivation Date',
      9: 'Inactivated Reason',
      10: 'Visiting Hours',
      11: 'Contact Phone',
      12: 'Location Cost Center',
    },
    LOC: {
      1: 'Primary Key Value',
      2: 'Location Description',
      3: 'Location Type',
      4: 'Organization Name',
      5: 'Location Address',
      6: 'Location Phone',
      7: 'License Number',
      8: 'Location Equipment',
      9: 'Location Service Code',
    },
    LRL: {
      1: 'Primary Key Value',
      2: 'Segment Action Code',
      3: 'Segment Unique Key',
      4: 'Location Relationship ID',
      5: 'Organizational Location Relationship Value',
      6: 'Patient Location Relationship Value',
    },
    MFA: {
      1: 'Record-Level Event Code',
      2: 'MFN Control ID',
      3: 'Event Completion Date/Time',
      4: 'MFN Record Level Error Return',
      5: 'Primary Key Value',
      6: 'Primary Key Value Type',
    },
    MFE: {
      1: 'Record-Level Event Code',
      2: 'MFN Control ID',
      3: 'Effective Date/Time',
      4: 'Primary Key Value',
      5: 'Primary Key Value Type',
    },
    MFI: {
      1: 'Master File Identifier',
      2: 'Master File Application Identifier',
      3: 'File-Level Event Code',
      4: 'Entered Date/Time',
      5: 'Effective Date/Time',
      6: 'Response Level Code',
    },
    MRG: {
      1: 'Prior Patient Identifier List',
      2: 'Prior Alternate Patient ID',
      3: 'Prior Patient Account Number',
      4: 'Prior Patient ID',
      5: 'Prior Visit Number',
      6: 'Prior Alternate Visit ID',
      7: 'Prior Patient Name',
    },
    MSA: {
      1: 'Acknowledgment Code',
      2: 'Message Control ID',
      3: 'Text Message',
      4: 'Expected Sequence Number',
      5: 'Delayed Acknowledgment Type',
      6: 'Error Condition',
    },
    MSH: {
      1: 'Field Separator',
      2: 'Encoding Characters',
      3: 'Sending Application',
      4: 'Sending Facility',
      5: 'Receiving Application',
      6: 'Receiving Facility',
      7: 'Date/Time Of Message',
      8: 'Security',
      9: 'Message Type',
      10: 'Message Control ID',
      11: 'Processing ID',
      12: 'Version ID',
      13: 'Sequence Number',
      14: 'Continuation Pointer',
      15: 'Accept Acknowledgment Type',
      16: 'Application Acknowledgment Type',
      17: 'Country Code',
      18: 'Character Set',
      19: 'Principal Language Of Message',
      20: 'Alternate Character Set Handling Scheme',
      21: 'Message Profile Identifier',
    },
    NCK: {
      1: 'System Date/Time',
    },
    NDS: {
      1: 'Notification Reference Number',
      2: 'Notification Date/Time',
      3: 'Notification Alert Severity',
      4: 'Notification Code',
    }, 
    NK1: {
      1: 'Set ID',
      2: 'NK Name',
      3: 'Relationship',
      4: 'Address',
      5: 'Phone Number',
      6: 'Business Phone Number',
      7: 'Contact Role',
      8: 'Start Date',
      9: 'End Date',
      10: 'Next of Kin / Associated Parties Job Title',
      11: 'Next of Kin / Associated Parties Job Code/Class',
      12: 'Next of Kin / Associated Parties Employee Number',
      13: 'Organization Name',
      14: 'Marital Status',
      15: 'Administrative Sex',
      16: 'Date/Time of Birth',
      17: 'Living Dependency',
      18: 'Ambulatory Status',
      19: 'Citizenship',
      20: 'Primary Language',
      21: 'Living Arrangement',
      22: 'Publicity Code',
      23: 'Protection Indicator',
      24: 'Student Indicator',
      25: 'Religion',
      26: "Mother's Maiden Name",
      27: 'Nationality',
      28: 'Ethnic Group',
      29: 'Contact Reason',
      30: "Contact Person's Name",
      31: "Contact Person's Telephone Number",
      32: "Contact Person's Address",
      33: "Next of Kin/Associated Party's Identifiers",
      34: 'Job Status',
      35: 'Race',
      36: 'Handicap',
      37: 'Contact Person Social Security Number',
      38: 'Next of Kin Birth Place',
      39: 'VIP Indicator',
    },
    NPU: {
      1: 'Bed Location',
      2: 'Bed Status',
    },
    NSC: {
      1: 'Application Change Type',
      2: 'Current CPU',
      3: 'Current Fileserver',
      4: 'Current Application',
      5: 'Current Facility',
      6: 'New CPU',
      7: 'New Fileserver',
      8: 'New Application',
      9: 'New Facility',
    },
    NST: {
      1: 'Statistics Available',
      2: 'Source Identifier',
      3: 'Source Type',
      4: 'Statistics Start',
      5: 'Statistics End',
      6: 'Receive Character Count',
      7: 'Send Character Count',
      8: 'Messages Received',
      9: 'Messages Sent',
      10: 'Checksum Errors Received',
      11: 'Length Errors Received',
      12: 'Other Errors Received',
      13: 'Connect Timeouts',
      14: 'Receive Timeouts',
      15: 'Application control-level Errors',
    },
    NTE: {
      1: 'Set ID',
      2: 'Source of Comment',
      3: 'Comment',
      4: 'Comment Type',
    }, 
    OBR: {
      1: 'Set ID',
      2: 'Placer Order Number',
      3: 'Filler Order Number',
      4: 'Universal Service Identifier',
      5: 'Priority',
      6: 'Requested Date/Time',
      7: 'Observation Date/Time',
      8: 'Observation End Date/Time',
      9: 'Collection Volume',
      10: 'Collector Identifier',
      11: 'Specimen Action Code',
      12: 'Danger Code',
      13: 'Relevant Clinical Information',
      14: 'Specimen Received Date/Time',
      15: 'Specimen Source',
      16: 'Ordering Provider',
      17: 'Order Callback Phone Number',
      18: 'Placer Field 1',
      19: 'Placer Field 2',
      20: 'Filler Field 1',
      21: 'Filler Field 2',
      22: 'Results Rpt/Status Chng - Date/Time',
      23: 'Charge to Practice',
      24: 'Diagnostic Serv Sect ID',
      25: 'Result Status',
      26: 'Parent Result',
      27: 'Quantity/Timing',
      28: 'Result Copies To',
      29: 'Parent',
      30: 'Transportation Mode',
      31: 'Reason for Study',
      32: 'Principal Result Interpreter',
      33: 'Assistant Result Interpreter',
      34: 'Technician',
      35: 'Transcriptionist',
      36: 'Scheduled Date/Time',
      37: 'Number of Sample Containers',
      38: 'Transport Logistics of Collected Sample',
      39: "Collector's Comment",
      40: 'Transport Arrangement Responsibility',
      41: 'Transport Arranged',
      42: 'Escort Required',
      43: 'Planned Patient Transport Comment',
      44: 'Procedure Code',
      45: 'Procedure Code Modifier',
      46: 'Placer Supplemental Service Information',
      47: 'Filler Supplemental Service Information',
      48: 'Medically Necessary Duplicate Procedure Reason',
      49: 'Result Handling',
      50: 'Parent Universal Service Identifier',
    },
    OBX: {
      1: 'Set ID',
      2: 'Value Type',
      3: 'Observation Identifier',
      4: 'Observation Sub-ID',
      5: 'Observation Value',
      6: 'Units',
      7: 'References Range',
      8: 'Abnormal Flags',
      9: 'Probability',
      10: 'Nature of Abnormal Test',
      11: 'Observation Result Status',
      12: 'Effective Date of Reference Range',
      13: 'User Defined Access Checks',
      14: 'Date/Time of the Observation',
      15: "Producer's ID",
      16: 'Responsible Observer',
      17: 'Observation Method',
      18: 'Equipment Instance Identifier',
      19: 'Date/Time of the Analysis',
      20: 'Reserved for harmonization with V2.6',
      21: 'Reserved for harmonization with V2.6',
      22: 'Reserved for harmonization with V2.6',
      23: 'Performing Organization Name',
      24: 'Performing Organization Address',
      25: 'Performing Organization Medical Director',
    },
    ODS: {
      1: 'Type',
      2: 'Service Period',
      3: 'Diet, Supplement, or Preference Code',
      4: 'Text Instruction',
    },
    ODT: {
      1: 'Tray Type',
      2: 'Service Period',
      3: 'Text Instruction',
    },
    OM1: {
      1: 'Sequence Number',
      2: "Producer's Service/Test/Observation ID",
      3: 'Permitted Data Types',
      4: 'Specimen Required',
      5: 'Producer ID',
      6: 'Observation Description',
      7: 'Other Service/Test/Observation IDs for the Observation',
      8: 'Other Names',
      9: 'Preferred Report Name for the Observation',
      10: 'Preferred Short Name or Mnemonic for Observation',
      11: 'Preferred Long Name for the Observation',
      12: 'Orderability',
      13: 'Identity of Instrument Used to Perform this Study',
      14: 'Coded Representation of Method',
      15: 'Portable Device Indicator',
      16: 'Observation Producing Department/Section',
      17: 'Telephone Number of Section',
      18: 'Nature of Service/Test/Observation',
      19: 'Report Subheader',
      20: 'Report Display Order',
      21: 'Date/Time Stamp for any change in Definition for the Observation',
      22: 'Effective Date/Time of Change',
      23: 'Typical Turn-Around Time',
      24: 'Processing Time',
      25: 'Processing Priority',
      26: 'Reporting Priority',
      27: 'Outside Site(s) Where Observation may be Performed',
      28: 'Address of Outside Site(s)',
      29: 'Phone Number of Outside Site',
      30: 'Confidentiality Code',
      31: 'Observations Required to Interpret the Observation',
      32: 'Interpretation of Observations',
      33: 'Contraindications to Observations',
      34: 'Reflex Tests/Observations',
      35: 'Rules that Trigger Reflex Testing',
      36: 'Fixed Canned Message',
      37: 'Patient Preparation',
      38: 'Procedure Medication',
      39: 'Factors that may Affect the Observation',
      40: 'Service/Test/Observation Performance Schedule',
      41: 'Description of Test Methods',
      42: 'Kind of Quantity Observed',
      43: 'Point Versus Interval',
      44: 'Challenge Information',
      45: 'Relationship Modifier',
      46: 'Target Anatomic Site Of Test',
      47: 'Modality Of Imaging Measurement',
    },
    OM2: {
      1: 'Sequence Number',
      2: 'Units of Measure',
      3: 'Range of Decimal Precision',
      4: 'Corresponding SI Units of Measure',
      5: 'SI Conversion Factor',
      6: 'Reference (Normal) Range - Ordinal and Continuous Observations',
      7: 'Critical Range for Ordinal and Continuous Observations',
      8: 'Absolute Range for Ordinal and Continuous Observations',
      9: 'Delta Check Criteria',
      10: 'Minimum Meaningful Increments',
    },
    OM3: {
      1: 'Sequence Number',
      2: 'Preferred Coding System',
      3: "Valid Coded 'Answers'",
      4: 'Normal Text/Codes for Categorical Observations',
      5: 'Abnormal Text/Codes for Categorical Observations',
      6: 'Critical Text/Codes for Categorical Observations',
      7: 'Value Type',
    },
    OM4: {
      1: 'Sequence Number',
      2: 'Derived Specimen',
      3: 'Container Description',
      4: 'Container Volume',
      5: 'Container Units',
      6: 'Specimen',
      7: 'Additive',
      8: 'Preparation',
      9: 'Special Handling Requirements',
      10: 'Normal Collection Volume',
      11: 'Minimum Collection Volume',
      12: 'Specimen Requirements',
      13: 'Specimen Priorities',
      14: 'Specimen Retention Time',
    },
    OM5: {
      1: 'Sequence Number',
      2: 'Test/Observations Included within an Ordered Test Battery',
      3: 'Observation ID Suffixes',
    },
    OM6: {
      1: 'Sequence Number',
      2: 'Derivation Rule',
    },
    OM7: {
      1: 'Sequence Number',
      2: 'Universal Service Identifier',
      3: 'Category Identifier',
      4: 'Category Description',
      5: 'Category Synonym',
      6: 'Effective Test/Service Start Date/Time',
      7: 'Effective Test/Service End Date/Time',
      8: 'Test/Service Default Duration Quantity',
      9: 'Test/Service Default Duration Units',
      10: 'Test/Service Default Frequency',
      11: 'Consent Indicator',
      12: 'Consent Identifier',
      13: 'Consent Effective Start Date/Time',
      14: 'Consent Effective End Date/Time',
      15: 'Consent Interval Quantity',
      16: 'Consent Interval Units',
      17: 'Consent Waiting Period Quantity',
      18: 'Consent Waiting Period Units',
      19: 'Effective Date/Time of Change',
      20: 'Entered By',
      21: 'Orderable-at Location',
      22: 'Formulary Status',
      23: 'Special Order Indicator',
      24: 'Primary Key Value - CDM',
    },
    ORC: {
      1: 'Order Control',
      2: 'Placer Order Number',
      3: 'Filler Order Number',
      4: 'Placer Group Number',
      5: 'Order Status',
      6: 'Response Flag',
      7: 'Quantity/Timing',
      8: 'Parent Order',
      9: 'Date/Time of Transaction',
      10: 'Entered By',
      11: 'Verified By',
      12: 'Ordering Provider',
      13: "Enterer's Location",
      14: 'Call Back Phone Number',
      15: 'Order Effective Date/Time',
      16: 'Order Control Code Reason',
      17: 'Entering Organization',
      18: 'Entering Device',
      19: 'Action By',
      20: 'Advanced Beneficiary Notice Code',
      21: 'Ordering Facility Name',
      22: 'Ordering Facility Address',
      23: 'Ordering Facility Phone Number',
      24: 'Ordering Provider Address',
      25: 'Order Status Modifier',
      26: 'Advanced Beneficiary Notice Override Reason',
      27: "Filler's Expected Availability Date/Time",
      28: 'Confidentiality Code',
      29: 'Order Type',
      30: 'Enterer Authorization Mode',
      31: 'Parent Universal Service Identifier',
    },
    ORG: {
      1: 'Set ID',
      2: 'Organization Unit Code',
      3: 'Organization Unit Type Code',
      4: 'Primary Org Unit Indicator',
      5: 'Practitioner Org Unit Identifier',
      6: 'Health Care Provider Type Code',
      7: 'Health Care Provider Classification Code',
      8: 'Health Care Provider Area of Specialization Code',
      9: 'Effective Date Range',
      10: 'Employment Status Code',
      11: 'Board Approval Indicator',
      12: 'Primary Care Physician Indicator',
    },
    OVR: {
      1: 'Business Rule Override Type',
      2: 'Business Rule Override Code',
      3: 'Override Comments',
      4: 'Override Entered By',
      5: 'Override Authorized By',
    },
    PCR: {
      1: 'Implicated Product',
      2: 'Generic Product',
      3: 'Product Class',
      4: 'Total Duration Of Therapy',
      5: 'Product Manufacture Date',
      6: 'Product Expiration Date',
      7: 'Product Implantation Date',
      8: 'Product Explantation Date',
      9: 'Single Use Device',
      10: 'Indication For Product Use',
      11: 'Product Problem',
      12: 'Product Serial/Lot Number',
      13: 'Product Available For Inspection',
      14: 'Product Evaluation Performed',
      15: 'Product Evaluation Status',
      16: 'Product Evaluation Results',
      17: 'Evaluated Product Source',
      18: 'Date Product Returned To Manufacturer',
      19: 'Device Operator Qualifications',
      20: 'Relatedness Assessment',
      21: 'Action Taken In Response To The Event',
      22: 'Event Causality Observations',
      23: 'Indirect Exposure Mechanism',
    },
    PD1: {
      1: 'Living Dependency',
      2: 'Living Arrangement',
      3: 'Patient Primary Facility',
      4: 'Patient Primary Care Provider Name and ID No.',
      5: 'Student Indicator',
      6: 'Handicap',
      7: 'Living Will Code',
      8: 'Organ Donor Code',
      9: 'Separate Bill',
      10: 'Duplicate Patient',
      11: 'Publicity Code',
      12: 'Protection Indicator',
      13: 'Protection Indicator Effective Date',
      14: 'Place of Worship',
      15: 'Advance Directive Code',
      16: 'Immunization Registry Status',
      17: 'Immunization Registry Status Effective Date',
      18: 'Publicity Code Effective Date',
      19: 'Military Branch',
      20: 'Military Rank/Grade',
      21: 'Military Status',
    },
    PDA: {
      1: 'Death Cause Code',
      2: 'Death Location',
      3: 'Death Certified Indicator',
      4: 'Death Certificate Signed Date/Time',
      5: 'Death Certified By',
      6: 'Autopsy Indicator',
      7: 'Autopsy Start and End Date/Time',
      8: 'Autopsy Performed By',
      9: 'Coroner Indicator',
    },
    PDC: {
      1: 'Manufacturer/Distributor',
      2: 'Country',
      3: 'Brand Name',
      4: 'Device Family Name',
      5: 'Generic Name',
      6: 'Model Identifier',
      7: 'Catalogue Identifier',
      8: 'Other Identifier',
      9: 'Product Code',
      10: 'Marketing Basis',
      11: 'Marketing Approval ID',
      12: 'Labeled Shelf Life',
      13: 'Expected Shelf Life',
      14: 'Date First Marketed',
      15: 'Date Last Marketed',
    },
    PEO: {
      1: 'Event Identifiers Used',
      2: 'Event Symptom/Diagnosis Code',
      3: 'Event Onset Date/Time',
      4: 'Event Exacerbation Date/Time',
      5: 'Event Improved Date/Time',
      6: 'Event Ended Date/Time',
      7: 'Event Location Occurred Address',
      8: 'Event Qualification',
      9: 'Event Serious',
      10: 'Event Expected',
      11: 'Event Outcome',
      12: 'Patient Outcome',
      13: 'Event Description From Others',
      14: 'Event From Original Reporter',
      15: 'Event Description From Patient',
      16: 'Event Description From Practitioner',
      17: 'Event Description From Autopsy',
      18: 'Cause Of Death',
      19: 'Primary Observer Name',
      20: 'Primary Observer Address',
      21: 'Primary Observer Telephone',
      22: "Primary Observer's Qualification",
      23: 'Confirmation Provided By',
      24: 'Primary Observer Aware Date/Time',
      25: "Primary Observer's identity May Be Divulged",
    },

    PES: {
      1: 'Sender Organization Name',
      2: 'Sender Individual Name',
      3: 'Sender Address',
      4: 'Sender Telephone',
      5: 'Sender Event Identifier',
      6: 'Sender Sequence Number',
      7: 'Sender Event Description',
      8: 'Sender Comment',
      9: 'Sender Aware Date/Time',
      10: 'Event Report Date',
      11: 'Event Report Timing/Type',
      12: 'Event Report Source',
      13: 'Event Reported To',
    },

    PID: {
      1: "Set ID - PID",
      2: "Patient ID",
      3: "Patient Identifier List",
      4: "Alternate Patient ID - PID",
      5: "Patient Name",
      6: "Mother's Maiden Name",
      7: "Date/Time of Birth",
      8: "Administrative Sex",
      9: "Patient Alias",
      10: "Race",
      11: "Patient Address",
      12: "County Code",
      13: "Phone Number - Home",
      14: "Phone Number - Business",
      15: "Primary Language",
      16: "Marital Status",
      17: "Religion",
      18: "Patient Account Number",
      19: "SSN Number - Patient",
      20: "Driver's License Number - Patient",
      21: "Mother's Identifier",
      22: "Ethnic Group",
      23: "Birth Place",
      24: "Multiple Birth Indicator",
      25: "Birth Order",
      26: "Citizenship",
      27: "Veterans Military Status",
      28: "Nationality",
      29: "Patient Death Date and Time",
      30: "Patient Death Indicator",
      31: "Identity Unknown Indicator",
      32: "Identity Reliability Code",
      33: "Last Update Date/Time",
      34: "Last Update Facility",
      35: "Species Code",
      36: "Breed Code",
      37: "Strain",
      38: "Production Class Code",
      39: "Tribal Citizenship",
    },

    PR1: {
      1: 'Set ID',
      2: 'Procedure Coding Method',
      3: 'Procedure Code',
      4: 'Procedure Description',
      5: 'Procedure Date/Time',
      6: 'Procedure Functional Type',
      7: 'Procedure Minutes',
      8: 'Anesthesiologist',
      9: 'Anesthesia Code',
      10: 'Anesthesia Minutes',
      11: 'Surgeon',
      12: 'Procedure Practitioner',
      13: 'Consent Code',
      14: 'Procedure Priority',
      15: 'Associated Diagnosis Code',
      16: 'Procedure Code Modifier',
      17: 'Procedure DRG Type',
      18: 'Tissue Type Code',
      19: 'Procedure Identifier',
      20: 'Procedure Action Code',
    },

    PRA: {
      1: 'Primary Key Value',
      2: 'Practitioner Group',
      3: 'Practitioner Category',
      4: 'Provider Billing',
      5: 'Specialty',
      6: 'Practitioner ID Numbers',
      7: 'Privileges',
      8: 'Date Entered Practice',
      9: 'Institution',
      10: 'Date Left Practice',
      11: 'Government Reimbursement Billing Eligibility',
      12: 'Set ID',
    },

    PRB: {
      1: 'Action Code',
      2: 'Action Date/Time',
      3: 'Problem ID',
      4: 'Problem Instance ID',
      5: 'Episode of Care ID',
      6: 'Problem List Priority',
      7: 'Problem Established Date/Time',
      8: 'Anticipated Problem Resolution Date/Time',
      9: 'Actual Problem Resolution Date/Time',
      10: 'Problem Classification',
      11: 'Problem Management Discipline',
      12: 'Problem Persistence',
      13: 'Problem Confirmation Status',
      14: 'Problem Life Cycle Status',
      15: 'Problem Life Cycle Status Date/Time',
      16: 'Problem Date of Onset',
      17: 'Problem Onset Text',
      18: 'Problem Ranking',
      19: 'Certainty of Problem (0-1)',
      20: 'Probability of Problem',
      21: 'Individual Awareness of Problem',
      22: 'Problem Prognosis',
      23: 'Individual Awareness of Prognosis',
      24: 'Family/Significant Other Awareness of Problem/Prognosis',
      25: 'Security/Sensitivity',
    },

    PRC: {
      1: 'Primary Key Value - PRC',
      2: 'Facility ID - PRC',
      3: 'Department',
      4: 'Valid Patient Classes',
      5: 'Price',
      6: 'Formula',
      7: 'Minimum Quantity',
      8: 'Maximum Quantity',
      9: 'Minimum Price',
      10: 'Maximum Price',
      11: 'Effective Start Date',
      12: 'Effective End Date',
      13: 'Price Override Flag',
      14: 'Billing Category',
      15: 'Chargeable Flag',
      16: 'Active/Inactive Flag',
      17: 'Cost',
      18: 'Charge On Indicator',
    },
    PRD: {
      1: 'Provider Role',
      2: 'Provider Name',
      3: 'Provider Address',
      4: 'Provider Location',
      5: 'Provider Communication Information',
      6: 'Preferred Method of Contact',
      7: 'Provider Identifiers',
      8: 'Effective Start Date of Provider Role',
      9: 'Effective End Date of Provider Role',
    },

    PSH: {
      1: 'Report Type',
      2: 'Report Form Identifier',
      3: 'Report Date',
      4: 'Report Interval Start Date',
      5: 'Report Interval End Date',
      6: 'Quantity Manufactured',
      7: 'Quantity Distributed',
      8: 'Quantity Distributed Method',
      9: 'Quantity Distributed Comment',
      10: 'Quantity in Use',
      11: 'Quantity in Use Method',
      12: 'Quantity in Use Comment',
      13: 'Number of Product Experience Reports Filed by Facility',
      14: 'Number of Product Experience Reports Filed by Distributor',
    },

    PTH: {
      1: 'Action Code',
      2: 'Pathway ID',
      3: 'Pathway Instance ID',
      4: 'Pathway Established Date/Time',
      5: 'Pathway Life Cycle Status',
      6: 'Change Pathway Life Cycle Status Date/Time',
    },

    PV1: {
      1: 'Set ID',
      2: 'Patient Class',
      3: 'Assigned Patient Location',
      4: 'Admission Type',
      5: 'Preadmit Number',
      6: 'Prior Patient Location',
      7: 'Attending Doctor',
      8: 'Referring Doctor',
      9: 'Consulting Doctor',
      10: 'Hospital Service',
      11: 'Temporary Location',
      12: 'Preadmit Test Indicator',
      13: 'Re-admission Indicator',
      14: 'Admit Source',
      15: 'Ambulatory Status',
      16: 'VIP Indicator',
      17: 'Admitting Doctor',
      18: 'Patient Type',
      19: 'Visit Number',
      20: 'Financial Class',
      21: 'Charge Price Indicator',
      22: 'Courtesy Code',
      23: 'Credit Rating',
      24: 'Contract Code',
      25: 'Contract Effective Date',
      26: 'Contract Amount',
      27: 'Contract Period',
      28: 'Interest Code',
      29: 'Transfer to Bad Debt Code',
      30: 'Transfer to Bad Debt Date',
      31: 'Bad Debt Agency Code',
      32: 'Bad Debt Transfer Amount',
      33: 'Bad Debt Recovery Amount',
      34: 'Delete Account Indicator',
      35: 'Delete Account Date',
      36: 'Discharge Disposition',
      37: 'Discharged to Location',
      38: 'Diet Type',
      39: 'Servicing Facility',
      40: 'Bed Status',
      41: 'Account Status',
      42: 'Pending Location',
      43: 'Prior Temporary Location',
      44: 'Admit Date/Time',
      45: 'Discharge Date/Time',
      46: 'Current Patient Balance',
      47: 'Total Charges',
      48: 'Total Adjustments',
      49: 'Total Payments',
      50: 'Alternate Visit ID',
      51: 'Visit Indicator',
      52: 'Other Healthcare Provider',
    },

    PV2: {
      1: 'Prior Pending Location',
      2: 'Accommodation Code',
      3: 'Admit Reason',
      4: 'Transfer Reason',
      5: 'Patient Valuables',
      6: 'Patient Valuables Location',
      7: 'Visit User Code',
      8: 'Expected Admit Date/Time',
      9: 'Expected Discharge Date/Time',
      10: 'Estimated Length of Inpatient Stay',
      11: 'Actual Length of Inpatient Stay',
      12: 'Visit Description',
      13: 'Referral Source Code',
      14: 'Previous Service Date',
      15: 'Employment Illness Related Indicator',
      16: 'Purge Status Code',
      17: 'Purge Status Date',
      18: 'Special Program Code',
      19: 'Retention Indicator',
      20: 'Expected Number of Insurance Plans',
      21: 'Visit Publicity Code',
      22: 'Visit Protection Indicator',
      23: 'Clinic Organization Name',
      24: 'Patient Status Code',
      25: 'Visit Priority Code',
      26: 'Previous Treatment Date',
      27: 'Expected Discharge Disposition',
      28: 'Signature on File Date',
      29: 'First Similar Illness Date',
      30: 'Patient Charge Adjustment Code',
      31: 'Recurring Service Code',
      32: 'Billing Media Code',
      33: 'Expected Surgery Date and Time',
      34: 'Military Partnership Code',
      35: 'Military Non-Availability Code',
      36: 'Newborn Baby Indicator',
      37: 'Baby Detained Indicator',
      38: 'Mode of Arrival Code',
      39: 'Recreational Drug Use Code',
      40: 'Admission Level of Care Code',
      41: 'Precaution Code',
      42: 'Patient Condition Code',
      43: 'Living Will Code',
      44: 'Organ Donor Code',
      45: 'Advance Directive Code',
      46: 'Patient Status Effective Date',
      47: 'Expected LOA Return Date/Time',
      48: 'Expected Pre-admission Testing Date/Time',
      49: 'Notify Clergy Code',
    },

    QAK: {
      1: 'Query Tag',
      2: 'Query Response Status',
      3: 'Message Query Name',
      4: 'Hit Count',
      5: 'This payload',
      6: 'Hits remaining',
    },

    QID: {
      1: 'Query Tag',
      2: "Message Query Name",
    },

    QPD: {
      1: 'Message Query Name',
      2: 'Query Tag',
      3: 'User Parameters (in successive fields)',
    },

    QRD: {
      1: 'Query Date/Time',
      2: 'Query Format Code',
      3: 'Query Priority',
      4: 'Query ID',
      5: 'Deferred Response Type',
      6: 'Deferred Response Date/Time',
      7: 'Quantity Limited Request',
      8: 'Who Subject Filter',
      9: 'What Subject Filter',
      10: 'What Department Data Code',
      11: 'What Data Code Value Qual.',
      12: 'Query Results Level',
    },


    QRF: {
      1: 'Where Subject Filter',
      2: 'When Data Start Date/Time',
      3: 'When Data End Date/Time',
      4: 'What User Qualifier',
      5: 'Other QRY Subject Filter',
      6: 'Which Date/Time Qualifier',
      7: 'Which Date/Time Status Qualifier',
      8: 'Date/Time Selection Qualifier',
      9: 'When Quantity/Timing Qualifier',
      10: 'Search Confidence Threshold',
    },

    QRI: {
      1: 'Candidate Confidence',
      2: 'Match Reason Code',
      3: 'Algorithm Descriptor',
    },

    RCP: {
      1: 'Query Priority',
      2: 'Quantity Limited Request',
      3: 'Response Modality',
      4: 'Execution and Delivery Time',
      5: 'Modify Indicator',
      6: 'Sort-by Field',
      7: 'Segment group inclusion',
    },

    RDF: {
      1: 'Number of Columns per Row',
      2: 'Column Description',
    },

    RDT: {
      1: 'Column Value',
    },

    RF1: {
      1: 'Referral Status',
      2: 'Referral Priority',
      3: 'Referral Type',
      4: 'Referral Disposition',
      5: 'Referral Category',
      6: 'Originating Referral Identifier',
      7: 'Effective Date',
      8: 'Expiration Date',
      9: 'Process Date',
      10: 'Referral Reason',
      11: 'External Referral Identifier',
    },

    RGS: {
      1: 'Set ID - RGS',
      2: 'Segment Action Code',
      3: 'Resource Group ID',
    },

    RMI: {
      1: 'Risk Management Incident Code',
      2: 'Date/Time Incident',
      3: 'Incident Type Code',
    },

    ROL: {
      1: 'Role Instance ID',
      2: 'Action Code',
      3: 'Role-ROL',
      4: 'Role Person',
      5: 'Role Begin Date/Time',
      6: 'Role End Date/Time',
      7: 'Role Duration',
      8: 'Role Action Reason',
      9: 'Provider Type',
      10: 'Organization Unit Type',
      11: 'Office/Home Address/Birthplace',
      12: 'Phone',
    },

    RQ1: {
      1: 'Anticipated Price',
      2: 'Manufacturer Identifier',
      3: 'Manufacturer\'s Catalog',
      4: 'Vendor ID',
      5: 'Vendor Catalog',
      6: 'Taxable',
      7: 'Substitute Allowed',
    },

    RQD: {
      1: 'Requisition Line Number',
      2: 'Item Code - Internal',
      3: 'Item Code - External',
      4: 'Hospital Item Code',
      5: 'Requisition Quantity',
      6: 'Requisition Unit of Measure',
      7: 'Dept. Cost Center',
      8: 'Item Natural Account Code',
      9: 'Deliver To ID',
      10: 'Date Needed',
    },

    RXA: {
      1: 'Give Sub-ID Counter',
      2: 'Administration Sub-ID Counter',
      3: 'Date/Time Start of Administration',
      4: 'Date/Time End of Administration',
      5: 'Administered Code',
      6: 'Administered Amount',
      7: 'Administered Units',
      8: 'Administered Dosage Form',
      9: 'Administration Notes',
      10: 'Administering Provider',
      11: 'Administered-at Location',
      12: 'Administered Per (Time Unit)',
      13: 'Administered Strength',
      14: 'Administered Strength Units',
      15: 'Substance Lot Number',
      16: 'Substance Expiration Date',
      17: 'Substance Manufacturer Name',
      18: 'Substance/Treatment Refusal Reason',
      19: 'Indication',
      20: 'Completion Status',
      21: 'Action Code - RXA',
      22: 'System Entry Date/Time',
      23: 'Administered Drug Strength Volume',
      24: 'Administered Drug Strength Volume Units',
      25: 'Administered Barcode Identifier',
      26: 'Pharmacy Order Type',
    },

    RXC: {
      1: 'RX Component Type',
      2: 'Component Code',
      3: 'Component Amount',
      4: 'Component Units',
      5: 'Component Strength',
      6: 'Component Strength Units',
      7: 'Supplementary Code',
      8: 'Component Drug Strength Volume',
      9: 'Component Drug Strength Volume Units',
    },

    RXD: {
      1: 'Dispense Sub-ID Counter',
      2: 'Dispense/Give Code',
      3: 'Date/Time Dispensed',
      4: 'Actual Dispense Amount',
      5: 'Actual Dispense Units',
      6: 'Actual Dosage Form',
      7: 'Prescription Number',
      8: 'Number of Refills Remaining',
      9: 'Dispense Notes',
      10: 'Dispensing Provider',
      11: 'Substitution Status',
      12: 'Total Daily Dose',
      13: 'Dispense-to Location',
      14: 'Needs Human Review',
      15: 'Pharmacy/Treatment Supplier\'s Special Dispensing Instructions',
      16: 'Actual Strength',
      17: 'Actual Strength Unit',
      18: 'Substance Lot Number',
      19: 'Substance Expiration Date',
      20: 'Substance Manufacturer Name',
      21: 'Indication',
      22: 'Dispense Package Size',
      23: 'Dispense Package Size Unit',
      24: 'Dispense Package Method',
      25: 'Supplementary Code',
      26: 'Initiating Location',
      27: 'Packaging/Assembly Location',
      28: 'Actual Drug Strength Volume',
      29: 'Actual Drug Strength Volume Units',
      30: 'Dispense to Pharmacy',
      31: 'Dispense to Pharmacy Address',
      32: 'Pharmacy Order Type',
      33: 'Dispense Type',
    },

    RXE: {
      1: 'Quantity/Timing',
      2: 'Give Code',
      3: 'Give Amount - Minimum',
      4: 'Give Amount - Maximum',
      5: 'Give Units',
      6: 'Give Dosage Form',
      7: 'Provider\'s Administration Instructions',
      8: 'Deliver-To Location',
      9: 'Substitution Status',
      10: 'Dispense Amount',
      11: 'Dispense Units',
      12: 'Number Of Refills',
      13: 'Ordering Provider\'s DEA Number',
      14: 'Pharmacist/Treatment Supplier\'s Verifier ID',
      15: 'Prescription Number',
      16: 'Number of Refills Remaining',
      17: 'Number of Refills/Doses Dispensed',
      18: 'D/T of Most Recent Refill or Dose Dispensed',
      19: 'Total Daily Dose',
      20: 'Needs Human Review',
      21: 'Pharmacy/Treatment Supplier\'s Special Dispensing Instructions',
      22: 'Give Per (Time Units)',
      23: 'Give Rate Amount',
      24: 'Give Rate Units',
      25: 'Give Strength',
      26: 'Give Strength Units',
      27: 'Give Indication',
      28: 'Dispense Package Size',
      29: 'Dispense Package Size Unit',
      30: 'Dispense Package Method',
      31: 'Supplementary Code',
      32: 'Original Order Date/Time',
      33: 'Give Drug Strength Volume',
      34: 'Give Drug Strength Volume Units',
      35: 'Controlled Substance Schedule',
      36: 'Formulary Status',
      37: 'Pharmaceutical Substance Alternative',
      38: 'Pharmacy of Most Recent Fill',
      39: 'Initial Dispense Amount',
      40: 'Dispensing Pharmacy',
      41: 'Dispensing Pharmacy Address',
      42: 'Deliver-to Patient Location',
      43: 'Deliver-to Address',
      44: 'Pharmacy Order Type',
    },

    RXG: {
      1: 'Give Sub-ID Counter',
      2: 'Dispense Sub-ID Counter',
      3: 'Quantity/Timing',
      4: 'Give Code',
      5: 'Give Amount - Minimum',
      6: 'Give Amount - Maximum',
      7: 'Give Units',
      8: 'Give Dosage Form',
      9: 'Administration Notes',
      10: 'Substitution Status',
      11: 'Dispense-to Location',
      12: 'Needs Human Review',
      13: 'Pharmacy/Treatment Supplier\'s Special Administration Instructions',
      14: 'Give Per (Time Unit)',
      15: 'Give Rate Amount',
      16: 'Give Rate Units',
      17: 'Give Strength',
      18: 'Give Strength Units',
      19: 'Substance Lot Number',
      20: 'Substance Expiration Date',
      21: 'Substance Manufacturer Name',
      22: 'Indication',
      23: 'Give Drug Strength Volume',
      24: 'Give Drug Strength Volume Units',
      25: 'Give Barcode Identifier',
      26: 'Pharmacy Order Type',
    },

    RXO: {
      1: 'Requested Give Code',
      2: 'Requested Give Amount - Minimum',
      3: 'Requested Give Amount - Maximum',
      4: 'Requested Give Units',
      5: 'Requested Dosage Form',
      6: 'Provider\'s Pharmacy/Treatment Instructions',
      7: 'Provider\'s Administration Instructions',
      8: 'Deliver-To Location',
      9: 'Allow Substitutions',
      10: 'Requested Dispense Code',
      11: 'Requested Dispense Amount',
      12: 'Requested Dispense Units',
      13: 'Number Of Refills',
      14: 'Ordering Provider\'s DEA Number',
      15: 'Pharmacist/Treatment Supplier\'s Verifier ID',
      16: 'Needs Human Review',
      17: 'Requested Give Per (Time Unit)',
      18: 'Requested Give Strength',
      19: 'Requested Give Strength Units',
      20: 'Indication',
      21: 'Requested Give Rate Amount',
      22: 'Requested Give Rate Units',
      23: 'Total Daily Dose',
      24: 'Supplementary Code',
      25: 'Requested Drug Strength Volume',
      26: 'Requested Drug Strength Volume Units',
      27: 'Pharmacy Order Type',
      28: 'Dispensing Interval',
    },

    RXR: {
      1: 'Route',
      2: 'Administration Site',
      3: 'Administration Device',
      4: 'Administration Method',
      5: 'Routing Instruction',
      6: 'Administration Site Modifier',
    },

    SAC: {
      1: 'External Accession Identifier',
      2: 'Accession Identifier',
      3: 'Container Identifier',
      4: 'Primary (parent) Container Identifier',
      5: 'Equipment Container Identifier',
      6: 'Specimen Source',
      7: 'Registration Date/Time',
      8: 'Container Status',
      9: 'Carrier Type',
      10: 'Carrier Identifier',
      11: 'Position in Carrier',
      12: 'Tray Type - SAC',
      13: 'Tray Identifier',
      14: 'Position in Tray',
      15: 'Location',
      16: 'Container Height',
      17: 'Container Diameter',
      18: 'Barrier Delta',
      19: 'Bottom Delta',
      20: 'Container Height/Diameter/Delta Units',
      21: 'Container Volume',
      22: 'Available Specimen Volume',
      23: 'Initial Specimen Volume',
      24: 'Volume Units',
      25: 'Separator Type',
      26: 'Cap Type',
      27: 'Additive',
      28: 'Specimen Component',
      29: 'Dilution Factor',
      30: 'Treatment',
      31: 'Temperature',
      32: 'Hemolysis Index',
      33: 'Hemolysis Index Units',
      34: 'Lipemia Index',
      35: 'Lipemia Index Units',
      36: 'Icterus Index',
      37: 'Icterus Index Units',
      38: 'Fibrin Index',
      39: 'Fibrin Index Units',
      40: 'System Induced Contaminants',
      41: 'Drug Interference',
      42: 'Artificial Blood',
      43: 'Special Handling Code',
      44: 'Other Environmental Factors',
    },

    SCH: {
      1: 'Placer Appointment ID',
      2: 'Filler Appointment ID',
      3: 'Occurrence Number',
      4: 'Placer Group Number',
      5: 'Schedule ID',
      6: 'Event Reason',
      7: 'Appointment Reason',
      8: 'Appointment Type',
      9: 'Appointment Duration',
      10: 'Appointment Duration Units',
      11: 'Appointment Timing Quantity',
      12: 'Placer Contact Person',
      13: 'Placer Contact Phone Number',
      14: 'Placer Contact Address',
      15: 'Placer Contact Location',
      16: 'Filler Contact Person',
      17: 'Filler Contact Phone Number',
      18: 'Filler Contact Address',
      19: 'Filler Contact Location',
      20: 'Entered By Person',
      21: 'Entered By Phone Number',
      22: 'Entered By Location',
      23: 'Parent Placer Appointment ID',
      24: 'Parent Filler Appointment ID',
      25: 'Filler Status Code',
      26: 'Placer Order Number',
      27: 'Filler Order Number',
    },

    SFT: {
      1: 'Software Vendor Organization',
      2: 'Software Certified Version or Release Number',
      3: 'Software Product Name',
      4: 'Software Binary ID',
      5: 'Software Product Information',
      6: 'Software Install Date',
    },

    SID: {
      1: 'Application / Method Identifier',
      2: 'Substance Lot Number',
      3: 'Substance Container Identifier',
      4: 'Substance Manufacturer Identifier',
    },

    SPM: {
      1: 'Set ID - SPM',
      2: 'Specimen ID',
      3: 'Specimen Parent IDs',
      4: 'Specimen Type',
      5: 'Specimen Type Modifier',
      6: 'Specimen Additives',
      7: 'Specimen Collection Method',
      8: 'Specimen Source Site',
      9: 'Specimen Source Site Modifier',
      10: 'Specimen Collection Site',
      11: 'Specimen Role',
      12: 'Specimen Collection Amount',
      13: 'Grouped Specimen Count',
      14: 'Specimen Description',
      15: 'Specimen Handling Code',
      16: 'Specimen Risk Code',
      17: 'Specimen Collection Date/Time',
      18: 'Specimen Received Date/Time',
      19: 'Specimen Expiration Date/Time',
      20: 'Specimen Availability',
      21: 'Specimen Reject Reason',
      22: 'Specimen Quality',
      23: 'Specimen Appropriateness',
      24: 'Specimen Condition',
      25: 'Specimen Current Quantity',
      26: 'Number of Specimen Containers',
      27: 'Container Type',
      28: 'Container Condition',
      29: 'Specimen Child Role',
    },

    SPR: {
      1: 'Query Tag',
      2: 'Query/Response Format Code',
      3: 'Stored Procedure Name',
      4: 'Input Parameter List',
    },

    STF: {
      1: 'Primary Key Value - STF',
      2: 'Staff Identifier List',
      3: 'Staff Name',
      4: 'Staff Type',
      5: 'Administrative Sex',
      6: 'Date/Time of Birth',
      7: 'Active/Inactive Flag',
      8: 'Department',
      9: 'Hospital Service - STF',
      10: 'Phone',
      11: 'Office/Home Address/Birthplace',
      12: 'Institution Activation Date',
      13: 'Institution Inactivation Date',
      14: 'Backup Person ID',
      15: 'E-Mail Address',
      16: 'Preferred Method of Contact',
      17: 'Marital Status',
      18: 'Job Title',
      19: 'Job Code/Class',
      20: 'Employment Status Code',
      21: 'Additional Insured on Auto',
      22: 'Driver\'s License Number - Staff',
      23: 'Copy Auto Ins',
      24: 'Auto Ins. Expires',
      25: 'Date Last DMV Review',
      26: 'Date Next DMV Review',
      27: 'Race',
      28: 'Ethnic Group',
      29: 'Re-activation Approval Indicator',
      30: 'Citizenship',
      31: 'Death Date and Time',
      32: 'Death Indicator',
      33: 'Institution Relationship Type Code',
      34: 'Institution Relationship Period',
      35: 'Expected Return Date',
      36: 'Cost Center Code',
      37: 'Generic Classification Indicator',
      38: 'Inactive Reason Code',
    },

    TCC: {
      1: 'Universal Service Identifier',
      2: 'Test Application Identifier',
      3: 'Specimen Source',
      4: 'Auto-Dilution Factor Default',
      5: 'Rerun Dilution Factor Default',
      6: 'Pre-Dilution Factor Default',
      7: 'Endogenous Content of Pre-Dilution Diluent',
      8: 'Inventory Limits Warning Level',
      9: 'Automatic Rerun Allowed',
      10: 'Automatic Repeat Allowed',
      11: 'Automatic Reflex Allowed',
      12: 'Equipment Dynamic Range',
      13: 'Units',
      14: 'Processing Type',
    },

    TCD: {
      1: 'Universal Service Identifier',
      2: 'Auto-Dilution Factor',
      3: 'Rerun Dilution Factor',
      4: 'Pre-Dilution Factor',
      5: 'Endogenous Content of Pre-Dilution Diluent',
      6: 'Automatic Repeat Allowed',
      7: 'Reflex Allowed',
      8: 'Analyte Repeat Status',
    },

    TQ1: {
      1: 'Set ID - TQ1',
      2: 'Quantity',
      3: 'Repeat Pattern',
      4: 'Explicit Time',
      5: 'Relative Time and Units',
      6: 'Service Duration',
      7: 'Start date/time',
      8: 'End date/time',
      9: 'Priority',
      10: 'Condition text',
      11: 'Text instruction',
      12: 'Conjunction',
      13: 'Occurrence duration',
      14: 'Total occurrences',
    },

    TQ2: {
      1: 'Set ID - TQ2',
      2: 'Sequence/Results Flag',
      3: 'Related Placer Number',
      4: 'Related Filler Number',
      5: 'Related Placer Group Number',
      6: 'Sequence Condition Code',
      7: 'Cyclic Entry/Exit Indicator',
      8: 'Sequence Condition Time Interval',
      9: 'Cyclic Group Maximum Number of Repeats',
      10: 'Special Service Request Relationship',
    },

    TXA: {
      1: 'Set ID - TXA',
      2: 'Document Type',
      3: 'Document Content Presentation',
      4: 'Activity Date/Time',
      5: 'Primary Activity Provider Code/Name',
      6: 'Origination Date/Time',
      7: 'Transcription Date/Time',
      8: 'Edit Date/Time',
      9: 'Originator Code/Name',
      10: 'Assigned Document Authenticator',
      11: 'Transcriptionist Code/Name',
      12: 'Unique Document Number',
      13: 'Parent Document Number',
      14: 'Placer Order Number',
      15: 'Filler Order Number',
      16: 'Unique Document File Name',
      17: 'Document Completion Status',
      18: 'Document Confidentiality Status',
      19: 'Document Availability Status',
      20: 'Document Storage Status',
      21: 'Document Change Reason',
      22: 'Authentication Person, Time Stamp',
      23: 'Distributed Copies (Code and Name of Recipients) ',
    },
    
    UB1: {
      1: 'Set ID - UB1',
      2: 'Blood Deductible (43)',
      3: 'Blood Furnished-Pints Of (40)',
      4: 'Blood Replaced-Pints (41)',
      5: 'Blood Not Replaced-Pints (42)',
      6: 'Co-Insurance Days (25)',
      7: 'Condition Code (35-39)',
      8: 'Covered Days (23)',
      9: 'Non Covered Days (24)',
      10: 'Value Amount and Code (46-49)',
      11: 'Number Of Grace Days (90)',
      12: 'Special Program Indicator (44)',
      13: 'PSRO/UR Approval Indicator (87)',
      14: 'PSRO/UR Approved Stay-Fm (88)',
      15: 'PSRO/UR Approved Stay-To (89)',
      16: 'Occurrence (28-32)',
      17: 'Occurrence Span (33)',
      18: 'Occur Span Start Date (33)',
      19: 'Occur Span End Date (33)',
      20: 'UB-82 Locator 2',
      21: 'UB-82 Locator 9',
      22: 'UB-82 Locator 27',
      23: 'UB-82 Locator 45',
    },

    UB2: {
      1: 'Set ID - UB2',
      2: 'Co-Insurance Days (9)',
      3: 'Condition Code (24-30)',
      4: 'Covered Days (7)',
      5: 'Non-Covered Days (8)',
      6: 'Value Amount and Code (39-41)',
      7: 'Occurrence Code and Date (32-35)',
      8: 'Occurrence Span Code/Dates (36)',
      9: 'UB92 Locator 2 (State)',
      10: 'UB92 Locator 11 (State)',
      11: 'UB92 Locator 31 (National)',
      12: 'Document Control Number',
      13: 'UB92 Locator 49 (National)',
      14: 'UB92 Locator 56 (State)',
      15: 'UB92 Locator 57 (National)',
      16: 'UB92 Locator 78 (State)',
      17: 'Special Visit Count',
    },

    URD: {
      1: 'R/U Date/Time',
      2: 'Report Priority',
      3: 'R/U Who Subject Definition',
      4: 'R/U What Subject Definition',
      5: 'R/U What Department Code',
      6: 'R/U Display/Print Locations',
      7: 'R/U Results Level',
    },

    URS: {
      1: 'R/U Where Subject Definition',
      2: 'R/U When Data Start Date/Time',
      3: 'R/U When Data End Date/Time',
      4: 'R/U What User Qualifier',
      5: 'R/U Other Results Subject Definition',
      6: 'R/U Which Date/Time Qualifier',
      7: 'R/U Which Date/Time Status Qualifier',
      8: 'R/U Date/Time Selection Qualifier',
      9: 'R/U Quantity/Timing Qualifier',
    },

    VAR: {
      1: 'Variance Instance ID',
      2: 'Documented Date/Time',
      3: 'Stated Variance Date/Time',
      4: 'Variance Originator',
      5: 'Variance Classification',
      6: 'Variance Description',
    },

    VTQ: {
      1: 'Query Tag',
      2: 'Query/Response Format Code',
      3: 'VT Query Name',
      4: 'Virtual Table Name',
      5: 'Selection Criteria',
    }

  };

  return descriptions[segmentType]?.[fieldIndex] ?? 'Field Description';
}
