/** Placeholder used so escaped \F\ in field values don't break segment split. */
const ESCAPED_FIELD_PLACEHOLDER = '\u0001';

/**
 * Split a segment line by field separator (|), respecting HL7 escape \F\ (literal pipe in value).
 * @param {string} segment - One segment line (e.g. "PID|1||123^abc")
 * @returns {string[]} [type, field1, field2, ...]
 */
function splitSegmentFields(segment) {
  const withPlaceholder = segment.replace(/\\F\\/g, ESCAPED_FIELD_PLACEHOLDER);
  const parts = withPlaceholder.split('|');
  return parts.map((value) => value.replace(new RegExp(ESCAPED_FIELD_PLACEHOLDER, 'g'), '|'));
}

/**
 * @param {string} message
 * @returns {{ type: string; raw: string; fields: Array<{ fieldNumber: number; value: string; description: string }> }[]}
 */
export const parseHL7Message = (message) => {
  if (!message) return [];

  const segments = message.split('\n').filter(Boolean);

  return segments.map((segment) => {
    const allParts = splitSegmentFields(segment);
    const [type, ...fieldValues] = allParts;

    return {
      type,
      raw: segment,
      fields: fieldValues.map((value, index) => ({
        fieldNumber: index + 1,
        value,
        description: getFieldDescription(type, index + 1),
      })),
    };
  });
};

/**
 * @param {string} segmentType
 * @param {number} fieldIndex
 * @returns {string}
 */
const getFieldDescription = (segmentType, fieldIndex) => {
  const descriptions = {
    MSH: {
      1: 'Field Separator',
      2: 'Encoding Characters',
      3: 'Sending Application',
      4: 'Sending Facility',
      5: 'Receiving Application',
      6: 'Receiving Facility',
      7: 'Message DateTime',
      8: 'Security',
      9: 'Message Type',
      10: 'Message Control ID',
      11: 'Processing ID',
      12: 'Version ID',
    },
    PID: {
      1: 'Set ID',
      2: 'Patient ID',
      3: 'Patient Identifier List',
      4: 'Alternate Patient ID',
      5: 'Patient Name',
      6: "Mother's Maiden Name",
      7: 'Date/Time of Birth',
      8: 'Administrative Sex',
      9: 'Patient Alias',
      10: 'Race',
      11: 'Patient Address',
      12: 'County Code',
      13: 'Phone Number - Home',
      14: 'Phone Number - Business',
      15: 'Primary Language',
      16: 'Martial Status',
      17: 'Religion',
      18: 'Patient Account Number',
      19: 'SSN Number - Patient',
      20: "Driver's License Number",
      21: "Mother's Identifier",
      22: 'Ethnic Group',
      23: 'Birth Place',
      24: 'Multiple Birth Indicator',
      25: 'Birth Order',
      26: 'Citizenship',
      27: 'Veterans Military Status',
      28: 'Nationality',
      29: 'Patient Death Date and Time',
      30: 'Patient Death Indicator',
    },
    OBR: {
      1: 'Set ID',
      2: 'Order Number',
      3: 'Filler Order Number',
      4: 'Universal Service Identifier',
      5: 'Priority',
      6: 'Requested Date/Time',
      7: 'Observation Date/Time',
      8: 'Observation End Date/Time',
      9: 'Collection Volume',
      10: 'Collector Identifier',
      11: 'Specimen Action Code',
      12: 'Danger Code',
      13: 'Relevant Clinical Information',
      14: 'Specimen Received Date/Time',
      15: 'Specimen Source',
      16: 'Ordering Provider',
      17: 'Order Callback Phone Number',
      18: 'Placer Field 1',
      19: 'Placer Field 2',
      20: 'Filler Field 1',
      21: 'Filler Field 2',
      22: 'Results Rpt/Status Chng - Date/Time',
      23: 'Charge to Practice',
      24: 'Diagnostic Serv Sect ID',
      25: 'Result Status',
      26: 'Parent Result',
      27: 'Quantity/Timing',
      28: 'Result Copies To',
      29: 'Parent',
      30: 'Transportation Mode',
      31: 'Reason for Study',
      32: 'Principal Result Interpreter',
      33: 'Assistant Result Interpreter',
      34: 'Technician',
      35: 'Transcriptionist',
      36: 'Scheduled Date/Time',
      37: 'Number of Sample Containers',
      38: 'Transport Logistics of Collected Sample',
      39: "Collector's Comment",
      40: 'Transport Arrangement Responsibility',
      41: 'Transport Arranged',
      42: 'Escort Required',
      43: 'Planned Patient Transport Comment',
      44: 'Procedure Code',
      45: 'Procedure Code Modifier',
      46: 'Placer Supplemental Service Information',
    },
    EVN: {
      1: 'Event Type Code',
      2: 'Recorded Date/Time',
      3: 'Date/Time Planned Event',
      4: 'Event Reason Code',
      5: 'Operator ID',
      6: 'Event Occurred',
    },
    OBX: {
      1: 'Set ID',
      2: 'Value Type',
      3: 'Observation Identifier',
      4: 'Observation Sub-ID',
      5: 'Observation Value',
      6: 'Units',
      7: 'References Range',
      8: 'Abnormal Flags',
      9: 'Probability',
      10: 'Nature of Abnormal Test',
      11: 'Observation Result Status',
      12: 'Effective Date of Reference Range',
      13: 'User Defined Access Checks',
      14: 'Date/Time of the Observation',
      15: "Producer's ID",
      16: 'Responsible Observer',
      17: 'Observation Method',
      18: 'Equipment Instance Identifier',
      19: 'Date/Time of the Analysis',
    },
    RXR: {
      1: 'Route',
      2: 'Site Administered',
      3: 'Administration Device',
      4: 'Administration Method',
      5: 'Routing Instructions',
    },
    RXA: {
      1: 'Give Sub-ID Counter',
      2: 'Administration Sub-ID Counter',
      3: 'Date/Time Start of Administration',
      4: 'Date/Time End of Administration',
      5: 'Administered Code',
      6: 'Administered Amount',
      7: 'Administered Units',
      8: 'Administering Provider',
      9: 'Administration Notes',
      10: 'Completion Status',
    },
    TQ1: {
      1: 'Set ID',
      2: 'Quantity',
      3: 'Repeat Pattern',
      4: 'Explicit Time',
      5: 'Relative Time and Units',
      6: 'Service Duration',
      7: 'Start date/time',
      8: 'End date/time',
      9: 'Priority',
      10: 'Condition text',
      11: 'Text instruction',
      12: 'Conjunction',
      13: 'Occurrence duration',
      14: 'Total occurrences',
    },
    FT1: {
      1: 'Set ID',
      2: 'Transaction ID',
      3: 'Transaction Batch ID',
      4: 'Transaction Date',
      5: 'Transaction Posting Date',
      6: 'Transaction Type',
      7: 'Transaction Code',
      8: 'Transaction Description',
      9: 'Transaction Description - Alt',
      10: 'Transaction Quantity',
      11: 'Transaction Amount - Extended',
      12: 'Transaction Amount - Unit',
      13: 'Department Code',
      14: 'Insurance Plan ID',
      15: 'Insurance Amount',
      16: 'Assigned Patient Location',
      17: 'Fee Schedule',
      18: 'Patient Type',
      19: 'Diagnosis Code - FT1',
      20: 'Performed By Code',
      21: 'Ordered By Code',
      22: 'Unit Cost',
      23: 'Filler Order Number',
      24: 'Entered By Code',
      25: 'Procedure Code',
      26: 'Procedure Code Modifier',
      27: 'Advanced Beneficiary Notice Code',
      28: 'Medically Necessary Duplicate Procedure Reason.',
      29: 'NDC Code',
      30: 'Payment Reference ID',
    },
    PR1: {
      1: 'Set ID',
      2: 'Procedure Coding Method',
      3: 'Procedure Code',
      4: 'Procedure Description',
      5: 'Procedure Date/Time',
      6: 'Procedure Functional Type',
      7: 'Procedure Minutes',
      8: 'Anesthesiologist',
      9: 'Anesthesia Code',
      10: 'Anesthesia Minutes',
      11: 'Surgeon',
      12: 'Procedure Practitioner',
      13: 'Consent Code',
      14: 'Procedure Priority',
      15: 'Associated Diagnosis Code',
      16: 'Procedure Code Modifier',
      17: 'Procedure DRG Type',
      18: 'Tissue Type Code',
      19: 'Procedure Identifier',
      20: 'Procedure Action Code',
    },
    TXA: {
      1: 'Set ID',
      2: 'Document Type',
      3: 'Document Content Presentation',
      4: 'Activity Date/Time',
      5: 'Primary Activity Provider Code/Name',
      6: 'Origination Date/Time',
      7: 'Transcription Date/Time',
      8: 'Edit Date/Time',
      9: 'Originator Code/Name',
      10: 'Assigned Document Authenticator',
      11: 'Transcriptionist Code/Name',
      12: 'Unique Document Number',
      13: 'Parent Document Number',
      14: 'Placer Order Number',
      15: 'Filler Order Number',
      16: 'Unique Document File Name',
      17: 'Document Completion Status',
      18: 'Document Confidentiality Status',
      19: 'Document Availibility Status',
      20: 'Document Storage Status',
      21: 'Document Change Reason',
      22: 'Authentication Person, Time Stamp',
      23: 'Distributed Copies',
    },
    RXD: {
      1: 'Dispense Sub-ID Counter',
      2: 'Dispense Amount',
      3: 'Dispense Units',
      4: 'Dispense Drug',
      5: 'Dispense Number of Refills',
      6: 'Dispense Quantity',
      7: 'Dispensing Pharmacy',
      8: 'Dispensing Date/Time',
      9: 'Dispensing Provider',
    },
    NK1: {
      1: 'Set ID',
      2: 'Next of Kin Name',
      3: 'Relationship to Patient',
      4: 'Address',
      5: 'Phone Number',
      6: 'Business Phone Number',
      7: 'Contact Role',
      8: 'Start Date',
      9: 'End Date',
      10: 'Next of Kin Job Title',
      11: 'Next of Kin Job Code/Class',
      12: 'Next of Kin Employee Number',
      13: 'Organization Name - NK1',
      14: 'Martial Status',
      15: 'Administrative Sex',
      16: 'Date of Birth',
    },
    AL1: {
      1: 'Set ID',
      2: 'Allergy Type',
      3: 'Allergy Code',
      4: 'Allergy Severity',
      5: 'Allergy Reaction',
      6: 'Identification of Allergy',
    },
    PV1: {
      1: 'Set ID',
      2: 'Patient Class',
      3: 'Assigned Patient Location',
      4: 'Admission Type',
      5: 'Preadmit Number',
      6: 'Prior Patient Location',
      7: 'Attending Doctor',
      8: 'Referring Doctor',
      9: 'Consulting Doctor',
      10: 'Hospital Service',
      11: 'Temporary Location',
      12: 'Pre-admit Test Indicator',
      13: 'Re-admission Indicatior',
      14: 'Admit Source',
      15: 'Ambulatory Status',
      16: 'VIP Indicator',
      17: 'Admitting Doctor',
      18: 'Patient Type',
      19: 'Visit Number',
      20: 'Financial Class',
      21: 'Charge Price Indicator',
      22: 'Courtesy Code',
      23: 'Credit Rating',
      24: 'Contract Code',
      25: 'Contract Effective Date',
      26: 'Contract Amount',
      27: 'Contract Period',
      28: 'Interest Code',
      29: 'Transfer to Bad Debt Code',
      30: 'Transfer to Bad Debt Date',
      31: 'Bad Debt Agency Code',
      32: 'Bad Debt Transfer Amount',
      33: 'Bad Debt Recovery Amount',
      34: 'Delete Account Indicator',
      35: 'Delete Account Date',
      36: 'Discharge Disposition',
      37: 'Discharged to Location',
      38: 'Diet Type',
      39: 'Servicing Facility',
      40: 'Bed Status',
      41: 'Account Status',
      42: 'Pending Location',
      43: 'Prior Temporary Location',
      44: 'Admit Date/Time',
      45: 'Discharge Date/Time',
      46: 'Current Patient Balance',
      47: 'Total Charges',
      48: 'Total Adjustments',
      49: 'Total Payments',
      50: 'Alternate Visit ID',
      51: 'Visit Indicator',
      52: 'Other Healthcare Provider',
      53: 'Visit Protection Indicator',
    },
    CCR: {
      1: 'Set ID',
      2: 'Patient ID',
      3: 'Date/Time of Care',
      4: 'Type of Care',
      5: 'Provider ID',
      6: 'Care Description',
      7: 'Clinical Outcome',
      8: 'Follow-Up Plan',
      9: 'Allergy Information',
      10: 'Medications',
      11: 'Procedure Codes',
      12: 'Diagnosis Codes',
    },
    ALL: {
      1: 'Set ID',
      2: 'Allergen Code',
      3: 'Allergen Name',
      4: 'Reaction Type',
      5: 'Severity',
      6: 'Onset Date/Time',
      7: 'Allergy Status',
      8: 'Allergy Comments',
    },
    IN1: {
      1: 'Set ID',
      2: 'Insurance Plan ID',
      3: 'Insurance Company Name',
      4: 'Insurance Company Address',
      5: 'Insurance Co Contact Person',
      6: 'Insurance Company Phone Number',
      7: 'Group Number',
      8: 'Group Name',
      9: "Insured's Group Employ ID",
      10: "Insured's Group Emp Name",
      11: 'Plan Effective Date',
      12: 'Plan expiration date',
      13: 'Authorization Number',
      14: 'Plan type',
      15: 'Name of insured',
      16: "Insured's Relation to Patient",
      17: "Insured's Date of Birth",
      18: "Insured's Address",
      19: 'Assignment of Benefits',
      20: 'Coordination of Benefits',
      21: 'Coord Of Ben. Priority',
      22: 'Notice Of Admission Flag',
      23: 'Notice Of Admission Date',
      24: 'Report Of Eligibility Flag',
      25: 'Report Of Eligibility Date',
      26: 'RElease Information Code',
      27: 'Pre-Admit Cert (PAC)',
      28: 'Verification Date',
      29: 'Verification By',
      30: 'Type of Agreement Code',
      31: 'Billing Status',
      32: 'Lifetime Reserve Days',
      33: 'Delay Before L.R. Days',
      34: 'Company Plan Code',
      35: 'Policy Number',
      36: 'Policy Deductible',
      37: 'Policy Limit Amount',
      38: 'Policy Limit Days',
      39: 'Room Rate - Semi-Private',
      40: 'Room Rate - Private',
      41: "Insured's Employment Status",
      42: "Insured's Administrative Sex",
      43: "Insured's Employer's Address",
      44: 'Verification Status',
      45: 'Prior Insurance Company ID',
      46: 'Coverage Type',
      47: 'Handicap',
      48: "Insured's ID Number",
      49: 'Signature Code',
      50: 'Signature Code Date',
      51: "Insured's Birth Place",
      52: 'VIP Indicator',
    },
  };

  return descriptions[segmentType]?.[fieldIndex] ?? 'Field Description';
};
